'use strict';
const $ = id => document.getElementById(id);
let token = '', currentRun = null;
const labels = {extractive:'证据摘录 · 非模型生成',model:'模型建议 · 待人工核对',model_error:'模型失败 · 已保留证据',no_evidence:'没有相关证据',insufficient:'证据不足'};
const statuses = {open:'待认领',in_progress:'处理中',waiting:'等待补充',resolved:'已解决'};
function eventText(event) {
  if(event.event!=='updated')return event.detail;
  try{const d=JSON.parse(event.detail);return `${statuses[d.from]} → ${statuses[d.status]} · ${d.assignee||'未分配'}${d.resolution?' · '+d.resolution:''}`;}catch{return '工单记录已更新';}
}
function notice(message) { $('notice').textContent = message; $('notice').hidden = !message; }
function node(tag, text, className) { const el=document.createElement(tag); if(text!==undefined)el.textContent=text; if(className)el.className=className; return el; }
async function api(path, options={}) {
  const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});
  const data=await response.json();
  if(!response.ok){if(response.status===401)$('settings').showModal();throw new Error(typeof data.detail==='string'?data.detail:'输入未通过校验，请检查长度和必填项');}
  return data;
}
async function safely(task) { try{notice('');await task();}catch(error){notice(error.message);} }
function button(text, action, className='secondary') { const b=node('button',text,className);b.type='button';b.addEventListener('click',()=>safely(action));return b; }
async function refreshHealth(){const h=await api('/health');$('model-status').textContent=h.model_configured?'模型已配置：'+h.model+' · 待实际调用验证':'当前为离线证据检索 · 未配置大模型';$('use-model').disabled=!h.model_configured;}
async function showView(view){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('page-title').textContent={desk:'客服工作台',knowledge:'知识资料',tickets:'人工工单',quality:'质量与反馈'}[view];if(view==='knowledge')await loadDocuments();if(view==='tickets')await loadTickets();if(view==='quality')await loadQuality();}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>safely(()=>showView(b.dataset.view))));
document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{$('question').value=b.dataset.question;$('question').focus();}));
async function seed(){const r=await api('/seed',{method:'POST'});notice('已载入 '+r.inserted+' 篇合成示例资料；重复点击不会重复导入。');await loadDocuments();}
$('seed').onclick=()=>safely(seed);$('seed-library').onclick=()=>safely(seed);
$('ask-form').addEventListener('submit',event=>{event.preventDefault();safely(async()=>{const b=$('ask-submit');b.disabled=true;b.textContent='正在检索与处理…';try{const result=await api('/ask',{method:'POST',body:JSON.stringify({question:$('question').value,audience:$('audience').value,use_model:$('use-model').checked})});renderRun(result);await loadHistory();}finally{b.disabled=false;b.textContent='检索并准备答复 →';}});});
function renderRun(run){currentRun=run;$('empty-answer').hidden=true;$('answer-result').hidden=false;$('answer-mode').textContent=labels[run.mode]||run.mode;$('answer-text').textContent=run.answer;$('result-meta').textContent=new Date(run.created_at).toLocaleString()+' · '+run.elapsed_ms+' ms · '+run.citations.length+' 条证据';$('feedback-note').value='';$('citations').replaceChildren();run.citations.forEach((c,i)=>{const card=node('article',undefined,'citation');card.append(node('strong',`[${i+1}] ${c.title}`),node('p',c.content),node('small',`${c.source} · 版本 ${c.version} · 片段 ${c.chunk+1} · 相关性分数 ${c.score}（非置信度）`));$('citations').append(card);});$('trace').textContent=JSON.stringify(run.trace,null,2);}
async function loadHistory(){const runs=await api('/runs');$('history-list').replaceChildren();if(!runs.length)$('history-list').append(node('p','暂无记录','muted'));runs.slice(0,8).forEach(r=>$('history-list').append(button(r.question,async()=>{renderRun(await api('/runs/'+r.id));await showView('desk');},'list-button')));}
for(const rating of ['helpful','unhelpful'])$(rating).onclick=()=>safely(async()=>{if(!currentRun)return;await api('/runs/'+currentRun.id+'/feedback',{method:'POST',body:JSON.stringify({rating,note:$('feedback-note').value})});notice('反馈已保存，可在质量与反馈中复盘。');});
$('export-run').onclick=()=>{if(!currentRun)return;const url=URL.createObjectURL(new Blob([JSON.stringify(currentRun,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='supportops-'+currentRun.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('create-ticket').onclick=()=>safely(async()=>{if(!currentRun)return;const t=await api('/tickets',{method:'POST',body:JSON.stringify({run_id:currentRun.id,title:currentRun.question.slice(0,200)})});await showView('tickets');await openTicket(t.id);notice(t.deduplicated?'该回答已有工单，已打开原工单。':'已创建工单，原问题与证据已关联。');});
$('doc-file').addEventListener('change',()=>safely(async()=>{const file=$('doc-file').files[0];if(!file)return;if(file.size>150000)throw new Error('文件超过 150KB，请拆分资料后导入');if(!/\.(txt|md)$/i.test(file.name))throw new Error('当前仅支持 TXT / Markdown 文件');const text=await file.text();if(text.length>50000)throw new Error('正文超过 50000 字符，请拆分资料');$('doc-content').value=text;$('doc-title').value=file.name.replace(/\.[^.]+$/,'');$('doc-source').value=file.name;}));
$('document-form').addEventListener('submit',e=>{e.preventDefault();safely(async()=>{await api('/documents',{method:'POST',body:JSON.stringify({title:$('doc-title').value,content:$('doc-content').value,source:$('doc-source').value||'用户导入',audience:$('doc-audience').value})});$('document-form').reset();await loadDocuments();notice('资料已保存，下次检索立即生效。');});});
async function loadDocuments(){const docs=await api('/documents');$('document-list').replaceChildren();if(!docs.length)$('document-list').append(node('p','尚无资料。添加自己的文档，或载入合成示例。','muted'));docs.forEach(d=>{const card=node('article',undefined,'doc-card');card.append(node('h3',d.title),node('span',d.audience==='public'?'对客知识':'内部资料','tag'),node('p',d.content.slice(0,160)+(d.content.length>160?'…':'')),node('p',d.source+' · '+d.content.length+' 字符'));card.append(button('删除资料',async()=>{if(!confirm('删除此资料？历史回答仍保留原有证据快照。'))return;await api('/documents/'+d.id,{method:'DELETE'});await loadDocuments();}));$('document-list').append(card);});}
async function loadTickets(){const tickets=await api('/tickets');$('ticket-board').replaceChildren();for(const [key,label] of Object.entries(statuses)){const col=node('section',undefined,'column');const list=tickets.filter(t=>t.status===key);col.append(node('h3',label+' · '+list.length));list.forEach(t=>{const b=button('',()=>openTicket(t.id),'ticket-card');b.append(node('strong',t.title),node('small',(t.priority==='high'?'高优先级':'常规')+' · '+(t.assignee||'未分配')+' · '+t.category));col.append(b);});$('ticket-board').append(col);}}
async function openTicket(id){const t=await api('/tickets/'+id);const panel=$('ticket-detail');panel.hidden=false;panel.replaceChildren();panel.append(node('h3',t.title),node('p','关键词规则分类建议：'+t.category+' / '+t.priority+' · 版本 '+t.version,'muted'));const form=node('form');const choices={open:['open','in_progress'],in_progress:['in_progress','waiting','resolved'],waiting:['waiting','in_progress'],resolved:['resolved','open']};const select=node('select');select.id='ticket-status';choices[t.status].forEach(s=>{const o=node('option',statuses[s]);o.value=s;select.append(o);});select.value=t.status;const who=node('input');who.id='ticket-assignee';who.value=t.assignee;who.maxLength=100;const resolution=node('textarea');resolution.id='ticket-resolution';resolution.value=t.resolution;resolution.maxLength=4000;resolution.rows=3;for(const [label,el] of [['状态',select],['处理人',who],['解决记录（标记已解决时必填）',resolution]]){const l=node('label',label);l.htmlFor=el.id;form.append(l,el);}const save=node('button','保存变更','primary');save.type='submit';const actions=node('div',undefined,'actions');actions.append(save,button('查看关联问题与证据',async()=>{renderRun(t.run);await showView('desk');}));form.append(actions);form.onsubmit=e=>{e.preventDefault();safely(async()=>{save.disabled=true;try{await api('/tickets/'+id,{method:'PATCH',body:JSON.stringify({version:t.version,status:select.value,assignee:who.value,resolution:resolution.value})});await loadTickets();await openTicket(id);notice('工单已更新。');}finally{save.disabled=false;}});};panel.append(form,node('h3','变更记录'));t.events.forEach(event=>panel.append(node('p',new Date(event.created_at).toLocaleString()+' · '+eventText(event),'muted')));panel.scrollIntoView({behavior:'smooth',block:'nearest'});}
$('refresh-tickets').onclick=()=>safely(loadTickets);
async function loadQuality(){const [m,bad]=await Promise.all([api('/metrics'),api('/badcases')]);$('metrics').replaceChildren();for(const [label,value] of [['知识资料',m.documents],['处理记录',m.runs],['人工工单',m.tickets],['负面反馈',m.feedback.unhelpful||0]]){const card=node('div',undefined,'metric');card.append(node('span',label),node('strong',String(value)));$('metrics').append(card);}$('badcases').replaceChildren();if(!bad.length)$('badcases').append(node('p','当前没有待复盘记录。','muted'));bad.forEach(r=>{const b=button('',async()=>{renderRun(await api('/runs/'+r.id));await showView('desk');},'list-button');b.append(node('strong',r.question),node('p',(labels[r.mode]||r.mode)+(r.note?' · '+r.note:''),'muted'));$('badcases').append(b);});}
$('refresh-quality').onclick=()=>safely(loadQuality);
$('connect').onclick=()=>$('settings').showModal();$('close-settings').onclick=()=>$('settings').close();$('settings-form').onsubmit=e=>{e.preventDefault();token=$('access-token').value;$('access-token').value='';$('settings').close();safely(async()=>{await refreshHealth();await loadHistory();notice('已连接工作台。');});};
safely(async()=>{await refreshHealth();await loadHistory();});
