'use strict';
const $=id=>document.getElementById(id);
let token='',pid=null,data=null,sourceId=null,selectedReport=null,mode='paste',modelReady=false;
let segmentBusy=false,stopSegments=false;
const states={draft:'待确认',approved:'已确认',rejected:'已退回'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
async function safe(fn){try{notice('');await fn();}catch(e){notice(e.message);}}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const d=await r.json();if(!r.ok){if(r.status===401&&!document.body.classList.contains('demo-mode')&&!$('settings').open)$('settings').showModal();throw Error(typeof d.detail==='string'?d.detail:'输入未通过校验，请检查必填项、格式与长度');}return d;}
const post=(path,body)=>api(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});
function button(text,fn,cls='quiet'){const b=el('button',text,cls);b.type='button';b.onclick=()=>safe(fn);return b;}
function options(target,values){const previous=$(target).value;$(target).replaceChildren(...values.map(v=>{const o=el('option',v);o.value=v;return o;}));if(values.includes(previous))$(target).value=previous;}
function tab(name){document.querySelectorAll('.tab-panel').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
async function projects(){const list=await api('/projects');$('projects').replaceChildren(...list.map(p=>button(p.title,()=>openProject(p.id),p.id===pid?'active':'')));}
async function openProject(id){const changed=pid!==id;pid=id;const loaded=await api('/projects/'+id);if(pid!==id)return;data=loaded;$('welcome').hidden=true;$('study').hidden=false;$('study-title').textContent=data.project.title;$('study-question').textContent=data.project.question;options('entity',data.project.entities);options('claim-dimension',data.project.dimensions);if(changed){sourceId=null;selectedReport=null;$('reader').hidden=true;$('report-preview').textContent='选择已有版本，或生成第一份报告。';$('download-md').disabled=true;$('download-json').disabled=true;tab('sources');}render();batchSources(changed);await Promise.all([projects(),loadBatches(id)]);}
function render(){const approved=data.claims.filter(c=>c.state==='approved').length;$('stats').replaceChildren(...[['来源快照',data.sources.length],['已确认结论',approved],['待补项',data.gaps.length],['待复核差异',data.differences.length]].map(([label,n])=>{const d=el('div',undefined,'stat');d.append(el('strong',String(n)),el('span',label));return d;}));renderSources();renderClaims();renderMatrix();renderReports();$('events').replaceChildren(...data.events.map(e=>el('p',new Date(e.created_at).toLocaleString()+' · '+e.detail)));if(sourceId){const s=data.sources.find(s=>s.id===sourceId);if(s)reader(s,false);}}
function renderSources(){$('source-list').replaceChildren();if(!data.sources.length)$('source-list').append(el('p','还没有来源。先保存一份真实材料。','muted'));for(const s of data.sources){const card=el('article',undefined,'source-card');card.append(el('span',s.entity,'badge'),el('span',s.archived?'已归档':s.method==='https'?'网页采集':'用户导入','badge'+(s.archived?' off':'')),el('h3',s.title),el('p',s.url||'未记录来源网址'),el('p',new Date(s.captured_at).toLocaleString()+' · '+s.content.length+' 字符'));card.append(button('阅读并关联证据',()=>reader(s)),button(s.archived?'恢复来源':'归档来源',async()=>{await api(`/projects/${pid}/sources/${s.id}`,{method:'PATCH',body:JSON.stringify({archived:!s.archived})});await openProject(pid);notice(s.archived?'来源已恢复。':'来源已归档，新报告将排除关联结论，旧报告保留原快照。');}));$('source-list').append(card);}}
function reader(s,scroll=true){sourceId=s.id;$('reader').hidden=false;$('reader-title').textContent=s.title;$('reader-meta').textContent=s.entity+' · 内容 SHA-256 '+s.sha256;$('reader-content').textContent=s.content;$('suggest').disabled=!modelReady||!!s.archived||segmentBusy;loadSegments(pid,s.id).catch(e=>notice(e.message));for(const control of $('claim-form').elements)control.disabled=!!s.archived;if(scroll)$('reader').scrollIntoView({behavior:'smooth',block:'start'});}
function renderClaims(){
 $('claim-list').replaceChildren();
 if(!data.claims.length)$('claim-list').append(el('p','阅读一份来源，然后摘取原文并添加候选结论。','muted'));
 for(const c of data.claims){
  const projectId=pid,s=data.sources.find(s=>s.id===c.source_id),card=el('article',undefined,'claim-card');
  card.append(el('span',states[c.state],'badge '+(c.state==='approved'?'ok':c.state==='draft'?'warn':'off')),el('span',c.entity+' / '+c.dimension,'badge'),el('h3',c.statement),el('blockquote',c.quote),el('p',(s?.title||'未知来源')+' · '+(c.origin==='model'?'模型起草':'人工起草')+' · 版本 '+c.version+(s?.archived?' · 来源已归档':''),'muted'));
  if(s){const context=el('details'),text=el('pre',undefined,'quote-context'),start=Math.max(0,c.quote_start-180),end=Math.min(s.content.length,c.quote_start+c.quote.length+180);context.append(el('summary','核对引用上下文 · 起点 '+c.quote_start));text.append(document.createTextNode(s.content.slice(start,c.quote_start)),el('mark',s.content.slice(c.quote_start,c.quote_start+c.quote.length)),document.createTextNode(s.content.slice(c.quote_start+c.quote.length,end)));context.append(text);card.append(context);}
  const label=el('label','审核说明'),input=el('input');input.id='note-'+c.id;input.maxLength=1000;input.value=c.review_note;input.placeholder='核对了哪些条件？为什么确认或退回？';label.htmlFor=input.id;card.append(label,input);
  const actions=el('div',undefined,'actions');
  for(const [state,text] of [['approved','确认事实'],['rejected','退回结论'],['draft','恢复待确认']]){const b=button(text,async()=>{if(input.value.trim().length<2)throw Error('请填写至少两个字符的审核说明');await api(`/projects/${projectId}/claims/${c.id}`,{method:'PATCH',body:JSON.stringify({version:c.version,state,note:input.value})});if(pid===projectId)await openProject(projectId);notice('审核状态已保存。');},state==='approved'?'secondary':'quiet');b.disabled=state===c.state||(state==='approved'&&!!s?.archived);actions.append(b);}
  actions.append(button('查看来源',()=>{tab('sources');reader(s);}));card.append(actions);
  const edit=el('details');edit.append(el('summary','修订结论与引用'));const form=el('form');form.append(el('p','保存后重新待审核，旧报告不变；来源不能在此替换。','muted'));
  function control(name,title,type,value){const label=el('label',title),n=el(type);n.name=name;n.id='edit-'+name+'-'+c.id;label.htmlFor=n.id;n.value=value;form.append(label,n);return n;}
  const dim=control('dimension','比较维度','select','');for(const v of data.project.dimensions){const option=el('option',v);option.value=v;dim.append(option);}dim.value=c.dimension;
  const statement=control('statement','修订后的结论','textarea',c.statement);statement.required=true;statement.minLength=2;statement.maxLength=1000;
  const quote=control('quote','修订后的连续原文','textarea',c.quote);quote.required=true;quote.minLength=4;quote.maxLength=4000;
  const offset=control('quote_start','全文起始位置（重复引用时必填，从0开始）','input','');offset.type='number';offset.min=0;offset.step=1;offset.placeholder=String(c.quote_start);
  const reason=control('note','修订原因','input','');reason.required=true;reason.minLength=2;reason.maxLength=1000;
  const save=el('button','保存修订，重新待审核','secondary');save.type='submit';save.disabled=!!s?.archived;form.append(save);form.onsubmit=e=>{e.preventDefault();safe(async()=>{save.disabled=true;try{await post(`/projects/${projectId}/claims/${c.id}/revisions`,{version:c.version,dimension:dim.value,statement:statement.value,quote:quote.value,quote_start:offset.value===''?null:Number(offset.value),note:reason.value});if(pid===projectId)await openProject(projectId);notice('修订已保存；需要重新审核后才进入新报告。');}finally{save.disabled=!!s?.archived;}});};edit.append(form);card.append(edit);
  const history=el('details'),entries=el('div');history.append(el('summary','版本与审核记录'),entries);history.addEventListener('toggle',()=>{if(history.open)safe(async()=>{const h=await api(`/projects/${projectId}/claims/${c.id}/versions`);entries.replaceChildren(el('p',h.note,'muted'));if(!h.versions.length)entries.append(el('p','此旧记录尚无版本历史，将在下次变更时保留当前基线。'));for(const v of h.versions){const a=el('article',undefined,'version-entry');a.append(el('strong',`v${v.version} · ${{created:'初始候选',reviewed:'审核变更',revised:'人工修订',baseline:'历史基线'}[v.action]} · ${states[v.snapshot.state]}`),el('p',v.snapshot.dimension+' / '+v.snapshot.statement),el('blockquote',v.snapshot.quote),el('p',v.note+' · '+new Date(v.created_at).toLocaleString(),'muted'));entries.append(a);}});});card.append(history);$('claim-list').append(card);
 }
}
function renderMatrix(){const head=el('thead'),tr=el('tr');tr.append(el('th','比较维度'),...data.project.entities.map(e=>el('th',e)));head.append(tr);const body=el('tbody');for(const row of data.matrix){const r=el('tr');r.append(el('th',row.dimension));for(const cell of row.cells){const td=el('td');if(cell.status==='gap')td.append(el('span','待补证据','badge warn'));if(cell.status==='review_difference')td.append(el('span','不同表述，需复核','badge warn'));for(const c of cell.claims)td.append(el('p',c.statement),button('核对引用',()=>{tab('sources');reader(data.sources.find(s=>s.id===c.source_id));}));r.append(td);}body.append(r);}$('comparison').replaceChildren(head,body);$('gaps').replaceChildren(...data.gaps.map(g=>el('span',g.entity+' / '+g.dimension,'badge warn')));if(!data.gaps.length)$('gaps').append(el('p','没有空白单元格；请继续核对来源时效和适用范围。','muted'));}
function renderReports(){$('report-list').replaceChildren(...data.reports.map(r=>button(new Date(r.created_at).toLocaleString(),async()=>{selectedReport=await api(`/projects/${pid}/reports/${r.id}`);$('report-preview').textContent=selectedReport.markdown;$('download-md').disabled=false;$('download-json').disabled=false;})));if(!data.reports.length)$('report-list').append(el('p','尚未生成报告版本。','muted'));}
for(const id of ['new-project','start-project'])$(id).onclick=()=>$('project-dialog').showModal();$('project-cancel').onclick=()=>$('project-dialog').close();
$('project-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const list=id=>$(id).value.split('\n').map(s=>s.trim()).filter(Boolean);const p=await post('/projects',{title:$('project-title').value,question:$('project-question').value,entities:list('project-entities'),dimensions:list('project-dimensions')});$('project-dialog').close();$('project-form').reset();await openProject(p.id);});};
function setMode(next){mode=next;const paste=mode==='paste';$('paste-fields').hidden=!paste;$('fetch-hint').hidden=paste;$('source-title').required=paste;$('source-content').required=paste;$('source-url').required=!paste;$('mode-paste').classList.toggle('selected',paste);$('mode-fetch').classList.toggle('selected',!paste);$('url-hint').textContent=paste?'（可选，仅记录，不自动访问）':'（公开 HTTPS 页面）';$('source-submit').textContent=paste?'保存来源快照 →':'采集并保存快照 →';}
$('mode-paste').onclick=()=>setMode('paste');$('mode-fetch').onclick=()=>setMode('fetch');
$('source-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const b=$('source-submit');b.disabled=true;try{const body={entity:$('entity').value,url:$('source-url').value};let s;if(mode==='fetch'){b.textContent='正在采集网页…';s=await post(`/projects/${pid}/fetch`,body);}else{s=await post(`/projects/${pid}/sources`,{...body,title:$('source-title').value,content:$('source-content').value,published_on:$('published-on').value||null});}await openProject(pid);reader(s);notice(s.deduplicated?'相同来源正文已经存在，已打开原快照。':'来源已保存，可以开始关联结论。');}finally{b.disabled=false;setMode(mode);}});};
$('claim-form').onsubmit=e=>{e.preventDefault();safe(async()=>{await post(`/projects/${pid}/claims`,{source_id:sourceId,dimension:$('claim-dimension').value,statement:$('claim-statement').value,quote:$('claim-quote').value});$('claim-statement').value='';$('claim-quote').value='';await openProject(pid);tab('claims');notice('候选结论已保存，审核通过后才进入报告。');});};
async function loadSegments(projectId,sid){
 const plan=await api(`/projects/${projectId}/sources/${sid}/segments`);
 if(pid!==projectId||sourceId!==sid)return plan;
 $('segment-summary').textContent=`已处理覆盖 ${plan.covered_characters}/${plan.total_characters} 字符 · ${plan.segments.filter(s=>s.state==='success').length}/${plan.segments.length} 段成功`+(plan.complete?' · 全部段已处理，仍需人工核对遗漏。':'');
 $('segment-list').replaceChildren();
 const source=data.sources.find(s=>s.id===sid);
 for(const w of plan.segments){const row=el('div',undefined,'segment-row');row.append(el('span',`第${w.index+1}段 [${w.start}, ${w.end}) · ${{pending:'未处理',running:'处理中',success:'已处理',failed:'失败，可重试'}[w.state]} · 尝试${w.attempts}次`));
 const preview=button('查看该段',()=>{$('reader-content').textContent=source.content.slice(w.start,w.end);notice(`正在阅读第${w.index+1}段；引用位置按原始全文记录。`);});row.append(preview);
 const run=button(w.state==='failed'?'重试该段':'处理该段',()=>processSegments(projectId,sid,w.index));run.disabled=segmentBusy||!modelReady||!!source.archived||['success','running'].includes(w.state);row.append(run);$('segment-list').append(row);}
 $('segment-list').append(button('恢复全文阅读',()=>{$('reader-content').textContent=source.content;}));return plan;
}
async function processSegments(projectId,sid,only=null){
 if(segmentBusy)return;segmentBusy=true;stopSegments=false;$('stop-segments').hidden=false;$('suggest').disabled=true;
 try{const plan=await loadSegments(projectId,sid);let count=0,failed=0;
 for(const w of plan.segments){if(stopSegments)break;if(w.state==='success'||(only!==null&&w.index!==only))continue;
 notice(`正在处理第${w.index+1}/${plan.segments.length}段，可在当前段结束后停止。`);
 try{const r=await post(`/projects/${projectId}/sources/${sid}/suggest?segment=${w.index}`);count+=r.claims.length;}catch(e){failed++;notice(`第${w.index+1}段未成功：${e.message}`);}await loadSegments(projectId,sid);}
 if(pid===projectId)await openProject(projectId);notice(`本次返回 ${count} 条候选（可能含已有去重条目），${failed} 段失败。候选均需审核。${stopSegments?'已停止，之后可继续。':'请在结论审核中核对遗漏及条件。'}`);
 }finally{segmentBusy=false;$('stop-segments').hidden=true;if(pid===projectId&&sourceId===sid){await loadSegments(projectId,sid);$('suggest').disabled=!modelReady||!!data.sources.find(s=>s.id===sid)?.archived;}}
}
$('stop-segments').onclick=()=>{stopSegments=true;notice('当前段结束后停止；已成功的分段会保留。');};
$('suggest').onclick=()=>safe(()=>processSegments(pid,sourceId));
$('refresh').onclick=()=>safe(()=>openProject(pid));$('generate-report').onclick=()=>safe(async()=>{selectedReport=await post(`/projects/${pid}/reports`);await openProject(pid);$('report-preview').textContent=selectedReport.markdown;$('download-md').disabled=false;$('download-json').disabled=false;notice('已生成独立报告快照。');});
function download(type){if(!selectedReport)return;const content=type==='md'?selectedReport.markdown:JSON.stringify(selectedReport,null,2);const url=URL.createObjectURL(new Blob([content],{type:type==='md'?'text/markdown':'application/json'}));const a=el('a');a.href=url;a.download='evidencebrief-'+selectedReport.id+'.'+type;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-md').onclick=()=>download('md');$('download-json').onclick=()=>download('json');
async function boot(){const h=await api('/health');modelReady=h.model_configured;$('health').textContent=modelReady?'模型已配置 · 可分段处理全文 · 候选须审核':'人工证据模式 · 模型未接入';await projects();}
$('settings-open').onclick=()=>$('settings').showModal();$('settings-close').onclick=()=>$('settings').close();$('settings-form').onsubmit=e=>{e.preventDefault();token=$('token').value;$('token').value='';$('settings').close();safe(boot);};safe(boot);
