'use strict';
const $=id=>document.getElementById(id);
let token='',pid=null,data=null,sourceId=null,selectedReport=null,mode='paste',modelReady=false;
const states={draft:'待确认',approved:'已确认',rejected:'已退回'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
async function safe(fn){try{notice('');await fn();}catch(e){notice(e.message);}}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});const d=await r.json();if(!r.ok){if(r.status===401&&!$('settings').open)$('settings').showModal();throw Error(typeof d.detail==='string'?d.detail:'输入未通过校验，请检查必填项、格式与长度');}return d;}
const post=(path,body)=>api(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});
function button(text,fn,cls='quiet'){const b=el('button',text,cls);b.type='button';b.onclick=()=>safe(fn);return b;}
function options(target,values){const previous=$(target).value;$(target).replaceChildren(...values.map(v=>{const o=el('option',v);o.value=v;return o;}));if(values.includes(previous))$(target).value=previous;}
function tab(name){document.querySelectorAll('.tab-panel').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
async function projects(){const list=await api('/projects');$('projects').replaceChildren(...list.map(p=>button(p.title,()=>openProject(p.id),p.id===pid?'active':'')));}
async function openProject(id){const changed=pid!==id;pid=id;data=await api('/projects/'+id);$('welcome').hidden=true;$('study').hidden=false;$('study-title').textContent=data.project.title;$('study-question').textContent=data.project.question;options('entity',data.project.entities);options('claim-dimension',data.project.dimensions);if(changed){sourceId=null;selectedReport=null;$('reader').hidden=true;$('report-preview').textContent='选择已有版本，或生成第一份报告。';$('download-md').disabled=true;$('download-json').disabled=true;tab('sources');}render();await projects();}
function render(){const approved=data.claims.filter(c=>c.state==='approved').length;$('stats').replaceChildren(...[['来源快照',data.sources.length],['已确认结论',approved],['待补项',data.gaps.length],['待复核差异',data.differences.length]].map(([label,n])=>{const d=el('div',undefined,'stat');d.append(el('strong',String(n)),el('span',label));return d;}));renderSources();renderClaims();renderMatrix();renderReports();$('events').replaceChildren(...data.events.map(e=>el('p',new Date(e.created_at).toLocaleString()+' · '+e.detail)));if(sourceId){const s=data.sources.find(s=>s.id===sourceId);if(s)reader(s,false);}}
function renderSources(){$('source-list').replaceChildren();if(!data.sources.length)$('source-list').append(el('p','还没有来源。先保存一份真实材料。','muted'));for(const s of data.sources){const card=el('article',undefined,'source-card');card.append(el('span',s.entity,'badge'),el('span',s.archived?'已归档':s.method==='https'?'网页采集':'用户导入','badge'+(s.archived?' off':'')),el('h3',s.title),el('p',s.url||'未记录来源网址'),el('p',new Date(s.captured_at).toLocaleString()+' · '+s.content.length+' 字符'));card.append(button('阅读并关联证据',()=>reader(s)),button(s.archived?'恢复来源':'归档来源',async()=>{await api(`/projects/${pid}/sources/${s.id}`,{method:'PATCH',body:JSON.stringify({archived:!s.archived})});await openProject(pid);notice(s.archived?'来源已恢复。':'来源已归档，新报告将排除关联结论，旧报告保留原快照。');}));$('source-list').append(card);}}
function reader(s,scroll=true){sourceId=s.id;$('reader').hidden=false;$('reader-title').textContent=s.title;$('reader-meta').textContent=s.entity+' · 内容 SHA-256 '+s.sha256;$('reader-content').textContent=s.content;$('suggest').disabled=!modelReady||!!s.archived;for(const control of $('claim-form').elements)control.disabled=!!s.archived;if(scroll)$('reader').scrollIntoView({behavior:'smooth',block:'start'});}
function renderClaims(){$('claim-list').replaceChildren();if(!data.claims.length)$('claim-list').append(el('p','阅读一份来源，然后摘取原文并添加候选结论。','muted'));for(const c of data.claims){const s=data.sources.find(s=>s.id===c.source_id);const card=el('article',undefined,'claim-card');card.append(el('span',states[c.state],'badge '+(c.state==='approved'?'ok':c.state==='draft'?'warn':'off')),el('span',c.entity+' / '+c.dimension,'badge'),el('h3',c.statement),el('blockquote',c.quote),el('p',(s?.title||'未知来源')+' · '+(c.origin==='model'?'模型候选':'人工添加')+' · 版本 '+c.version+(s?.archived?' · 来源已归档':''),'muted'));const label=el('label','审核说明');const input=el('input');input.id='note-'+c.id;input.maxLength=1000;input.value=c.review_note;input.placeholder='核对了哪些条件？为什么确认或退回？';label.htmlFor=input.id;card.append(label,input);const actions=el('div',undefined,'actions');for(const [state,text] of [['approved','确认事实'],['rejected','退回结论'],['draft','恢复待确认']]){const b=button(text,async()=>{if(input.value.trim().length<2)throw Error('请填写至少两个字符的审核说明');await api(`/projects/${pid}/claims/${c.id}`,{method:'PATCH',body:JSON.stringify({version:c.version,state,note:input.value})});await openProject(pid);notice('审核状态已保存。');},state==='approved'?'secondary':'quiet');b.disabled=state===c.state||(state==='approved'&&!!s?.archived);actions.append(b);}actions.append(button('查看来源',()=>{tab('sources');reader(s);}));card.append(actions);$('claim-list').append(card);}}
function renderMatrix(){const head=el('thead'),tr=el('tr');tr.append(el('th','比较维度'),...data.project.entities.map(e=>el('th',e)));head.append(tr);const body=el('tbody');for(const row of data.matrix){const r=el('tr');r.append(el('th',row.dimension));for(const cell of row.cells){const td=el('td');if(cell.status==='gap')td.append(el('span','待补证据','badge warn'));if(cell.status==='review_difference')td.append(el('span','不同表述，需复核','badge warn'));for(const c of cell.claims)td.append(el('p',c.statement),button('核对引用',()=>{tab('sources');reader(data.sources.find(s=>s.id===c.source_id));}));r.append(td);}body.append(r);}$('comparison').replaceChildren(head,body);$('gaps').replaceChildren(...data.gaps.map(g=>el('span',g.entity+' / '+g.dimension,'badge warn')));if(!data.gaps.length)$('gaps').append(el('p','没有空白单元格；请继续核对来源时效和适用范围。','muted'));}
function renderReports(){$('report-list').replaceChildren(...data.reports.map(r=>button(new Date(r.created_at).toLocaleString(),async()=>{selectedReport=await api(`/projects/${pid}/reports/${r.id}`);$('report-preview').textContent=selectedReport.markdown;$('download-md').disabled=false;$('download-json').disabled=false;})));if(!data.reports.length)$('report-list').append(el('p','尚未生成报告版本。','muted'));}
for(const id of ['new-project','start-project'])$(id).onclick=()=>$('project-dialog').showModal();$('project-cancel').onclick=()=>$('project-dialog').close();
$('project-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const list=id=>$(id).value.split('\n').map(s=>s.trim()).filter(Boolean);const p=await post('/projects',{title:$('project-title').value,question:$('project-question').value,entities:list('project-entities'),dimensions:list('project-dimensions')});$('project-dialog').close();$('project-form').reset();await openProject(p.id);});};
function setMode(next){mode=next;const paste=mode==='paste';$('paste-fields').hidden=!paste;$('fetch-hint').hidden=paste;$('source-title').required=paste;$('source-content').required=paste;$('source-url').required=!paste;$('mode-paste').classList.toggle('selected',paste);$('mode-fetch').classList.toggle('selected',!paste);$('url-hint').textContent=paste?'（可选，仅记录，不自动访问）':'（公开 HTTPS 页面）';$('source-submit').textContent=paste?'保存来源快照 →':'采集并保存快照 →';}
$('mode-paste').onclick=()=>setMode('paste');$('mode-fetch').onclick=()=>setMode('fetch');
$('source-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const b=$('source-submit');b.disabled=true;try{const body={entity:$('entity').value,url:$('source-url').value};let s;if(mode==='fetch'){b.textContent='正在采集网页…';s=await post(`/projects/${pid}/fetch`,body);}else{s=await post(`/projects/${pid}/sources`,{...body,title:$('source-title').value,content:$('source-content').value,published_on:$('published-on').value||null});}await openProject(pid);reader(s);notice(s.deduplicated?'相同来源正文已经存在，已打开原快照。':'来源已保存，可以开始关联结论。');}finally{b.disabled=false;setMode(mode);}});};
$('claim-form').onsubmit=e=>{e.preventDefault();safe(async()=>{await post(`/projects/${pid}/claims`,{source_id:sourceId,dimension:$('claim-dimension').value,statement:$('claim-statement').value,quote:$('claim-quote').value});$('claim-statement').value='';$('claim-quote').value='';await openProject(pid);tab('claims');notice('候选结论已保存，审核通过后才进入报告。');});};
$('suggest').onclick=()=>safe(async()=>{const b=$('suggest');b.disabled=true;b.textContent='正在提取并校验引用…';try{const r=await post(`/projects/${pid}/sources/${sourceId}/suggest`);await openProject(pid);tab('claims');notice('保存 '+r.claims.length+' 条模型候选，均需人工核对。');}finally{b.textContent='用免费 / 本地模型提取候选';b.disabled=!modelReady;}});
$('refresh').onclick=()=>safe(()=>openProject(pid));$('generate-report').onclick=()=>safe(async()=>{selectedReport=await post(`/projects/${pid}/reports`);await openProject(pid);$('report-preview').textContent=selectedReport.markdown;$('download-md').disabled=false;$('download-json').disabled=false;notice('已生成独立报告快照。');});
function download(type){if(!selectedReport)return;const content=type==='md'?selectedReport.markdown:JSON.stringify(selectedReport,null,2);const url=URL.createObjectURL(new Blob([content],{type:type==='md'?'text/markdown':'application/json'}));const a=el('a');a.href=url;a.download='evidencebrief-'+selectedReport.id+'.'+type;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-md').onclick=()=>download('md');$('download-json').onclick=()=>download('json');
async function boot(){const h=await api('/health');modelReady=h.model_configured;$('health').textContent=modelReady?'模型已配置 · 候选须审核':'人工证据模式 · 模型未接入';await projects();}
$('settings-open').onclick=()=>$('settings').showModal();$('settings-close').onclick=()=>$('settings').close();$('settings-form').onsubmit=e=>{e.preventDefault();token=$('token').value;$('token').value='';$('settings').close();safe(boot);};safe(boot);
