'use strict';
const $=s=>document.querySelector(s), id=document.body.dataset.project, key='ai-exhibit-v1-'+id;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let config,state;
function message(text){$('#status').textContent=text;}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));message('已保存在当前浏览器。');}catch{message('浏览器存储不可用；本次仍可操作，请导出后保存。');}}
function initial(){return {source:config.source,records:config.candidates.map((r,i)=>({...r,id:i+1,status:'pending',version:1})),snapshots:[],activity:[],secondary:id==='changelens'?'基础版支持网页知识库。\n团队版可接入邮件和工单。\n试用期为七天。':id==='evaldesk'?'正向\n中性\n中性':'',result:null};}
function log(action){state.activity.push({at:new Date().toISOString(),action});state.activity=state.activity.slice(-100);}
function action(label,fn,secondary=false){const b=node('button',label);b.type='button';if(secondary)b.className='secondary';b.onclick=()=>{try{fn();}catch(e){message(e.message);}};return b;}
function input(label,value,multiline=true){const wrap=node('label',label),field=node(multiline?'textarea':'input');field.value=value;field.maxLength=12000;wrap.append(field);return [wrap,field];}
function download(snapshot){const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=id+'-browser-demo-'+snapshot.number+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function snapshots(){const root=$('#snapshots');root.replaceChildren();for(const s of state.snapshots){const row=node('div');row.className='actions';row.append(node('span',`#${s.number} · ${s.at} · ${s.records.length} 条`),action('下载 JSON',()=>download(s)));root.append(row);}}
function freeze(){const approved=state.records.filter(r=>r.status==='approved');if(!approved.length)throw Error('请先确认至少一条内容。');if(state.snapshots.length>=20)throw Error('演示最多保留 20 份快照，请先下载并清除记录。');const snapshot=JSON.parse(JSON.stringify({schema:1,mode:'browser-demo',synthetic:true,model_called:false,project:id,number:state.snapshots.length+1,at:new Date().toISOString(),source:state.source,secondary:state.secondary,records:approved,activity:state.activity}));state.snapshots.push(snapshot);log('冻结交付 #'+snapshot.number);persist();snapshots();message('已冻结当前已确认内容；未确认和已拒绝的内容不进入交付。');}
function renderRecords(root){root.replaceChildren();if(!state.records.length)root.append(node('p','尚无候选，请运行上方操作或手动添加。'));for(const r of state.records){const card=node('article');card.className='record';card.append(node('p',`#${r.id} · v${r.version} · ${r.status==='approved'?'已确认':r.status==='rejected'?'已拒绝':'待核对'}`));const [ql,q]=input('引用原文',r.quote),[tl,t]=input(id==='studydeck'?'问题与答案（可修订）':'内容 / 人工判断',r.text);card.append(ql,tl);const controls=node('div');controls.className='actions';controls.append(action('保存修订',()=>{if(!q.value.trim()||!t.value.trim())throw Error('引用和内容均不能为空。');r.quote=q.value.trim();r.text=t.value.trim();r.status='pending';r.version++;log('修订候选 #'+r.id);persist();render();}),action('核对引用并确认',()=>{if(q.value!==r.quote||t.value!==r.text)throw Error('有未保存修改，请先保存修订。');if(!r.quote||!state.source.includes(r.quote))throw Error('引用未在当前原文中找到；请修订引用。');if(id==='contentbench'&&!r.text.includes('请勿盛装沸水'))throw Error('稿件缺少必带说明：请勿盛装沸水。请修订后再确认。');if(id==='applytrack'&&(r.text.includes('待关联经历')||r.text.trim().length<12))throw Error('请先填写自己的真实项目经历，再保存修订。');r.status='approved';r.version++;log('人工确认 #'+r.id);persist();render();}),action('拒绝',()=>{r.status='rejected';r.version++;log('拒绝 #'+r.id);persist();render();},true));card.append(controls);if(id==='studydeck'&&r.status==='approved'){const answer=node('pre',r.text);answer.hidden=true;card.append(action('自测：显示 / 隐藏答案',()=>{answer.hidden=!answer.hidden;},true),answer);}root.append(card);}}
function addRecord(text,quote){state.records.push({id:Math.max(0,...state.records.map(r=>r.id))+1,text,quote,status:'pending',version:1});}
function render(){const root=$('#workspace');root.replaceChildren();const columns=node('div');columns.className='columns';const left=node('section'),right=node('section');left.append(node('h2','01 / 原始材料'));const [sl,source]=input('材料原文（合成示例，可编辑）',state.source);left.append(sl,action('保存材料',()=>{if(!source.value.trim())throw Error('材料不能为空。');state.source=source.value;for(const r of state.records){r.status='pending';r.version++;}state.result=null;log('保存材料，候选需重新审核');persist();render();}));left.append(node('p','修改原文后，所有候选恢复待核对；已冻结快照不变。'));
 if(['changelens','evaldesk'].includes(id)){const [l,f]=input(id==='changelens'?'新版本原文':'候选输出（每行对应一例）',state.secondary);left.append(l,action('保存对照内容',()=>{state.secondary=f.value;state.records=[];log('更新对照内容');persist();render();}));}
 if(id==='supportops'){const [l,q]=input('检索问题 / 关键词','退款',false),hits=node('div');left.append(l,action('检索本页知识',()=>{hits.replaceChildren();const terms=q.value.trim().split(/\s+/).filter(Boolean);const lines=state.source.split('\n').filter(line=>terms.length&&terms.every(term=>line.includes(term)));if(!lines.length)hits.append(node('p','未找到匹配。请尝试“退款”“发票”或“密码”；本页为关键词检索。'));for(const line of lines){hits.append(node('blockquote',line),action('转为人工处理候选',()=>{addRecord('请核实用户情况后处理。',line);persist();render();}));}}),hits);}
 if(id==='databrief')left.append(action('按渠道汇总订单数',()=>{const lines=state.source.trim().split(/\r?\n/);if(lines.shift()!=='渠道,订单数')throw Error('请保留表头“渠道,订单数”。此演示只支持无引号的两列 CSV。');const sums=new Map();for(const line of lines){const cells=line.split(',');if(cells.length!==2||!cells[0].trim()||!/^\d+$/.test(cells[1].trim()))throw Error('每行须为“渠道,非负整数”，空值和其他格式不会静默忽略。');const n=Number(cells[1]);if(!Number.isSafeInteger(n)||!Number.isSafeInteger((sums.get(cells[0])||0)+n))throw Error('数值超出演示安全整数范围。');sums.set(cells[0],(sums.get(cells[0])||0)+n);}if(!sums.size)throw Error('至少需要一行数据。');state.records=[];addRecord([...sums].sort((a,b)=>b[1]-a[1]).map(([k,v])=>`${k}：${v} 单`).join('\n'),state.source);log('浏览器执行分组求和');persist();render();}));
 if(id==='changelens')left.append(action('计算逐行差异',()=>{state.records=[];const before=state.source.split('\n'),after=state.secondary.split('\n');for(let i=0;i<Math.max(before.length,after.length);i++){if(before[i]!==after[i])addRecord(`第 ${i+1} 行：\n旧：${before[i]??'（空）'}\n新：${after[i]??'（删除）'}\n影响：待人工解释。`,before[i]||state.source);}log('按行位置比较（不识别移动）');persist();render();message(state.records.length?'差异已生成，请补充影响判断。':'两个版本逐行相同。');}));
 if(id==='evaldesk')left.append(action('运行精确匹配',()=>{const expected=state.source.trim().split('\n'),actual=state.secondary.trim().split('\n');if(expected.length!==actual.length)throw Error('期望标签与输出行数不一致。');state.records=[];expected.forEach((v,i)=>addRecord(`用例 ${i+1}｜期望：${v}｜实际：${actual[i]}｜${v===actual[i]?'通过':'失败'}`,v));log('本地精确匹配 '+actual.filter((v,i)=>v===expected[i]).length+'/'+expected.length);persist();render();message('完成逐行精确匹配；不是模型准确率评估。');}));
 right.append(node('h2','02 / 人工核对与修订'),node('p',config.candidates.length?'预置候选由人工编写，用于展示核对流程。引用通过不代表结论正确。':'结果由浏览器规则计算，确认后才能交付。'));const list=node('div');renderRecords(list);right.append(list);right.append(action('添加手工候选',()=>{if(state.records.length>=50)throw Error('演示最多 50 条候选。');addRecord('请填写判断或任务。','请粘贴材料中的连续原文。');persist();render();},true));columns.append(left,right);root.append(columns);const history=node('details');history.append(node('summary','本机操作记录'),node('pre',state.activity.map(e=>e.at+' '+e.action).join('\n')||'暂无操作'));root.append(history);snapshots();}
async function start(){const response=await fetch(id+'.json');if(!response.ok)throw Error('样例载入失败，请刷新或返回案例页。');config=await response.json();try{const saved=JSON.parse(localStorage.getItem(key));state=saved&&Array.isArray(saved.records)&&Array.isArray(saved.snapshots)&&Array.isArray(saved.activity)&&typeof saved.source==='string'?saved:initial();}catch{state=initial();}render();message('已载入合成样例 / 本机记录。此页不调用大模型。');$('#freeze').onclick=()=>{try{freeze();}catch(e){message(e.message);}};$('#reset').onclick=()=>{if(!confirm('恢复样例会清除当前演示操作和快照。请先下载需要保留的记录。'))return;state=initial();persist();render();};$('#clear').onclick=()=>{if(!confirm('清除本机保存的该项目演示记录？'))return;localStorage.removeItem(key);state=initial();render();message('已清除本机记录；当前显示未保存的初始样例。');};}
start().catch(e=>message(e.message));
