'use strict';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let current=null, modelReady=false;
const names={draft:'待确认',rejected:'已退回',open:'待开始',in_progress:'进行中',blocked:'受阻',done:'已完成',cancelled:'已取消'};
const next={open:['in_progress','blocked','cancelled'],in_progress:['blocked','done','cancelled'],blocked:['open','in_progress','cancelled'],done:['open'],cancelled:['open']};
function notice(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';}
async function api(path,data){const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(sessionStorage.getItem('ma-token')||'')},body:data===undefined?undefined:JSON.stringify(data)});const json=await r.json();if(!r.ok)throw Error(typeof json.detail==='string'?json.detail:'输入格式错误，请检查字段与长度');return json;}
function action(b,fn){b.addEventListener('click',async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}});}
function show(id){for(const name of ['welcome','create','study','board'])$('#'+name).hidden=name!==id;}
function options(select,values,selected='',blank=true){select.replaceChildren();if(blank){const o=el('option','未明确');o.value='';select.append(o);}for(const value of values){const o=el('option',value);o.value=value;o.selected=value===selected;select.append(o);}}
function field(parent,label,type='text',value=''){const l=el('label',label),i=el(type==='textarea'?'textarea':type==='select'?'select':'input');if(!['textarea','select'].includes(type))i.type=type;i.value=value;if(type==='textarea')i.rows=2;l.append(i);parent.append(l);return i;}
function check(parent,text,checked=false){const l=el('label',undefined,'check'),i=el('input');i.type='checkbox';i.checked=checked;l.append(i,el('span',text));parent.append(l);return i;}
async function list(){const rows=await api('/meetings');$('#meetings').replaceChildren();rows.forEach(m=>{const b=el('button',m.title,current?.id===m.id?'active':'');action(b,()=>load(m.id));$('#meetings').append(b);});}
async function load(id){current=await api('/meetings/'+id);show('study');$('#meeting-title').textContent=current.title;$('#meeting-meta').textContent=current.meeting_date+' · '+current.attendees.join('、');$('#transcript').textContent=current.transcript;$('#hash').textContent='原文 SHA256 '+current.sha256;$('#extract').disabled=!modelReady;renderSegments();options($('#candidate-owner'),current.attendees);$('#candidates').replaceChildren();$('#action-count').textContent=current.actions.length+' 项';current.actions.forEach(candidateCard);if(!current.actions.length)$('#candidates').append(el('p','尚无候选。可以模型提取，也可以从原文手工关联。','muted'));$('#runs').replaceChildren(...current.runs.map(r=>el('pre',r.state+'\n'+JSON.stringify(r.trace,null,2))));$('#events').replaceChildren(...current.events.map(e=>el('p',`${new Date(e.created_at).toLocaleString()} · ${e.event} · ${e.detail}`,'event')));await list();}
function candidateCard(a){const card=el('article',undefined,'draft'),head=el('div',undefined,'section-head');head.append(el('h3',a.title),el('span',names[a.state],'tag'));card.append(head,el('blockquote',a.quote,'body'),el('p',`${a.origin==='model'?'模型候选':'手工候选'} · 原文字符 ${a.quote_start} 起 · 提议负责人 ${a.proposed_owner||'未明确'} · 期限词 ${a.due_phrase||'未明确'}`,'muted'));
if(a.state==='draft'){const title=field(card,'确认行动内容','text',a.title),owner=field(card,'确认负责人','select');options(owner,current.attendees,a.proposed_owner);const due=field(card,'确认截止日期','date',a.proposed_due),none=check(card,'会议未约定截止日期（确认后进入无期限任务）'),note=field(card,'确认 / 退回说明（至少 5 字）','textarea');const bar=el('div',undefined,'actions');for(const [decision,label] of [['confirm','确认并进入任务看板'],['reject','退回候选']]){const b=el('button',label,decision==='reject'?'secondary':'');action(b,async()=>{await api('/actions/'+a.id+'/review',{version:a.version,decision,title:title.value,owner:owner.value,due_date:due.value||null,no_deadline:none.checked,note:note.value});await load(current.id);notice('已保存确认结果');});bar.append(b);}card.append(bar);}else card.append(el('p',`${a.owner||'未分配'} · ${a.due_date||'无期限'} · ${a.review_note}`));$('#candidates').append(card);}
async function board(){const f=$('#filter').elements;const query=new URLSearchParams({owner:f.owner.value,overdue:String(f.overdue.checked)});const rows=await api('/board?'+query);show('board');$('#board-summary').textContent=`筛选结果 ${rows.length} 项 · ${rows.filter(x=>x.overdue).length} 项逾期`;$('#board-items').replaceChildren();for(const state of ['open','in_progress','blocked','done','cancelled']){const group=rows.filter(x=>x.state===state);if(!group.length)continue;const section=el('section');section.append(el('h3',names[state]+' · '+group.length));group.forEach(a=>section.append(taskCard(a)));$('#board-items').append(section);}if(!rows.length)$('#board-items').append(el('p','没有符合筛选条件的已确认任务。','panel'));}
function taskCard(a){const card=el('article',undefined,'draft'),head=el('div',undefined,'section-head');head.append(el('h3',a.title),el('span',a.overdue?'已逾期':names[a.state],a.overdue?'issues':'tag'));card.append(head,el('p',`${a.owner} · ${a.due_date||'无期限'} · ${a.meeting_title}`,'muted'));const source=el('details');source.append(el('summary','查看原文与确认说明'),el('blockquote',a.quote,'body'),el('p',a.review_note));card.append(source);const state=field(card,'下一步状态','select');for(const v of next[a.state]){const o=el('option',names[v]);o.value=v;state.append(o);}const note=field(card,'进展 / 完成证据 / 调整原因（至少 5 字）','textarea');const update=el('button','保存进展');action(update,async()=>{await api('/actions/'+a.id+'/state',{version:a.version,state:state.value,note:note.value});await board();notice('进展已记录');});card.append(update);
if(['open','in_progress','blocked'].includes(a.state)){const d=el('details');d.append(el('summary','调整负责人或期限'));const owner=field(d,'新负责人','select');options(owner,a.attendees,a.owner,false);const due=field(d,'新截止日期','date',a.due_date),none=check(d,'明确无截止日期',!a.due_date),save=el('button','保存调整','secondary');action(save,async()=>{await api('/actions/'+a.id+'/schedule',{version:a.version,owner:owner.value,due_date:due.value||null,no_deadline:none.checked,note:note.value});await board();notice('调整已记录，保留原负责人和期限');});d.append(save);card.append(d);}if(a.completion_note)card.append(el('p','完成记录：'+a.completion_note,'good'));return card;}
$('#new').onclick=()=>show('create');action($('#board-nav'),board);$('#filter').onsubmit=e=>{e.preventDefault();board().catch(e=>notice(e.message,true));};
$('#sample').onclick=()=>{show('create');const f=$('#meeting-form').elements;f.title.value='发布周会 · 合成会议';f.meeting_date.value='2026-09-23';f.attendees.value='小林\n小周';f.transcript.value='小林：我明天完成接口文档。\n小周：我下周一检查发布清单。\n小林：先不要发布公告，等检查完成再讨论。';};
$('#text-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>240000)throw Error('文件超过 240KB，请拆分记录');const text=await file.text();if(text.length>80000)throw Error('文字超过 80000 字符');$('#meeting-form').elements.transcript.value=text;notice('文件已读入，请核对乱码、发言人和日期后保存');}catch(e){notice(e.message,true);}};
$('#meeting-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=e.target.elements;const m=await api('/meetings',{title:f.title.value,meeting_date:f.meeting_date.value,attendees:f.attendees.value.split('\n').map(x=>x.trim()).filter(Boolean),transcript:f.transcript.value});await load(m.id);notice('原文快照已保存');}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
$('#candidate-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=e.target.elements;await api('/meetings/'+current.id+'/candidates',{title:f.title.value,quote:f.quote.value,owner:f.owner.value,due_phrase:f.due_phrase.value});e.target.reset();await load(current.id);notice('候选已保存，尚未进入执行');}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
function segmentStatus(){
 const part=current?.segments[Number($('#extract-segment').value)];if(!part)return;
 const chars=Array.from(current.transcript);
 $('#segment-preview').textContent=chars.slice(part.start,part.end).join('');
 const completed=current.segments.filter(p=>p.state==='success').length;
 $('#segment-status').textContent=`已成功处理 ${completed}/${current.segments.length} 段 · 当前字符 ${part.start}–${part.end}（不含末位） · ${part.chars} 字符。${part.state==='success'&&part.last_attempt==='failed'?'最近重试失败，保留此前成功覆盖；失败轨迹仍可查看。':''}${part.hard_split?'本段因长句硬切，跨边界语义需核对。':''}处理成功不代表找全承诺；旧版前缀提取记录不计入新分段覆盖。`;
}
function renderSegments(){
 const selected=$('#extract-segment').value;
 $('#extract-segment').replaceChildren();
 for(const p of current.segments){const option=el('option',`第 ${p.index+1} 段 · ${{pending:'未处理',success:'已处理',failed:'失败可重试'}[p.state]} · ${p.chars} 字符`);option.value=p.index;$('#extract-segment').append(option);}
 if(current.segments.some(p=>String(p.index)===selected))$('#extract-segment').value=selected;
 $('#rerun-segment').checked=false;segmentStatus();
}
$('#extract-segment').onchange=()=>{$('#rerun-segment').checked=false;segmentStatus();};
action($('#extract'),async()=>{
 const id=current.id,segment=Number($('#extract-segment').value),rerun=$('#rerun-segment').checked;
 notice(`正在处理第 ${segment+1} 段，请核对之后的候选…`);
 try{const r=await api('/meetings/'+id+'/extract',{segment,rerun});if(current?.id===id)await load(id);notice(`${r.reused?'复用已完成记录，未重复调用模型':'本段处理完成'} · ${r.actions.length} 项候选，仍需核对承诺、负责人和期限。`);}
 catch(e){if(current?.id===id)await load(id);throw e;}
});
document.querySelectorAll('[data-export]').forEach(b=>action(b,async()=>{const format=b.dataset.export;const r=await fetch('/api/export/'+format,{headers:{Authorization:'Bearer '+(sessionStorage.getItem('ma-token')||'')}});if(!r.ok)throw Error('导出失败，请检查访问令牌');const url=URL.createObjectURL(await r.blob());const a=el('a');a.href=url;a.download='meeting-actions.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));
$('#auth').onclick=()=>{const token=prompt('工作台令牌（仅当前标签页保存）');if(token!==null){sessionStorage.setItem('ma-token',token);location.reload();}};
(async()=>{try{const h=await api('/health');modelReady=h.model_configured;$('#model-status').textContent=modelReady?'免费模型已配置 · 每段最多 4000 字符，逐段核对':'模型未配置 · 可手工关联行动项';await list();}catch(e){notice(e.message,true);}})();
