'use strict';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const names={draft:'待确认',open:'待处理',doing:'进行中',blocked:'受阻',done:'已完成',cancelled:'已取消',rejected:'已退回'};
let selected=null,editing=null,loadSequence=0,configured=false;
function notice(text,error=false){$('#notice').textContent=text;$('#notice').className=error?'error':'';}
async function api(path,data,raw=false){const headers={Authorization:'Bearer '+(sessionStorage.getItem('it-token')||'')};if(data!==undefined)headers['Content-Type']=raw?'message/rfc822':'application/json';const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:raw?data:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(typeof result.detail==='string'?result.detail:'输入格式不正确，请检查必填项');return result;}
function action(b,fn){b.addEventListener('click',async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}});}
function button(text,fn,cls='quiet'){const b=el('button',text,cls);b.type='button';action(b,fn);return b;}
function field(label,type,value=''){const wrap=el('label',label),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value;wrap.append(input);return {wrap,input};}
function reset(){editing=null;$('#candidate').reset();$('#revision-note').hidden=true;$('#candidate').elements.note.required=false;$('#cancel-edit').hidden=true;$('#editor-title').textContent='手工补充候选';$('#save').textContent='保存待确认候选';}
async function list(){const data=await api('/messages');$('#messages').replaceChildren(...data.map(m=>button(m.subject,()=>load(m.id),m.id===selected?.id?'active':'')));}
async function load(id){const sequence=++loadSequence;const [source,runs]=await Promise.all([api('/messages/'+id),api('/messages/'+id+'/model-runs')]);if(sequence!==loadSequence)return;selected=source;reset();$('#welcome').hidden=true;$('#study').hidden=false;$('#subject').textContent=source.subject;$('#metadata').textContent=`${source.sender||'未记录发件人'} → ${source.recipients||'未记录收件人'} · ${source.date_header||'未记录日期'}`;$('#body').textContent=source.body;$('#hash').textContent=`原邮件 SHA-256：${source.sha256}\n正文 SHA-256：${source.body_sha256}\n正文类型：${source.body_type}`;$('#warnings').replaceChildren(...source.warnings.map(w=>el('p',w,'warning')));$('#conflicts').replaceChildren();for(const cid of source.message_id_conflicts){$('#conflicts').append(button('核对同 Message-ID 的冲突邮件',()=>load(cid)));}if(source.message_id_conflicts.length)$('#conflicts').prepend(el('p','发现内容不同的同 ID 邮件。确认任务前必须逐一核对。','warning'));$('#generate').disabled=!configured;$('#tasks').replaceChildren();source.tasks.forEach(t=>renderTask(t,source));if(!source.tasks.length)$('#tasks').append(el('p','暂无候选。模型可能遗漏，请核对全文并手工补充。','warning'));$('#counts').textContent=`${source.tasks.length} 项 · ${source.tasks.filter(t=>t.state==='draft').length} 待确认`;$('#run-list').replaceChildren(...runs.map(r=>{const d=el('details');d.append(el('summary',`${new Date(r.created_at).toLocaleString()} · ${r.state==='succeeded'?'协议检查通过':'失败'} · ${r.model}`),el('p','协议通过不代表无遗漏。'+r.error),el('pre',r.raw||'模型未返回可记录内容'));return d;}));await list();}
async function refresh(id){if(selected?.id===id)await load(id);}
function showQuote(t,source){if(selected?.id!==source.id)return;const start=t.quote_start;$('#body').replaceChildren(document.createTextNode(source.body.slice(0,start)),el('mark',source.body.slice(start,start+t.quote.length)),document.createTextNode(source.body.slice(start+t.quote.length)));$('#body').querySelector('mark').scrollIntoView({block:'center',behavior:'smooth'});}
function renderTask(t,source){const card=el('article',undefined,'task'),head=el('div',undefined,'section-head');head.append(el('h3',t.title),el('span',`${names[t.state]} · v${t.version}`,'tag'));card.append(head,el('p',`${t.origin==='model'?'模型候选':'人工候选'} · 已确认负责人：${t.owner||'未确认'} · 期限：${t.due_date||'未指定'}`,'muted'),el('blockquote',t.quote));if(t.proposed_owner||t.proposed_due)card.append(el('p',`模型建议（未确认）：${t.proposed_owner||'负责人未知'} / ${t.proposed_due||'期限未知'}`,'warning'));
 const actions=el('div',undefined,'actions');actions.append(button('定位原文',()=>showQuote(t,source)),button('修订并重新确认',()=>{editing={id:t.id,version:t.version,mid:source.id};const f=$('#candidate').elements;f.title.value=t.title;f.quote.value=t.quote;f.quote_start.value=t.quote_start;f.note.value='';f.note.required=true;$('#revision-note').hidden=false;$('#cancel-edit').hidden=false;$('#editor-title').textContent='修订任务 · 保存后恢复待确认';$('#save').textContent='保存修订版';$('#editor-title').scrollIntoView({behavior:'smooth'});}));card.append(actions);
 if(t.state==='draft'){const form=el('form'),owner=field('确认负责人','text'),due=field('确认截止日期（无期限可留空）','date'),note=field('确认说明（至少5字；无期限请说明）','textarea');owner.input.required=true;owner.input.maxLength=120;note.input.required=true;note.input.minLength=5;note.input.maxLength=1000;form.append(owner.wrap,due.wrap,note.wrap);let conflict=null;if(source.message_id_conflicts.length){conflict=field('我已逐一核对上述冲突邮件','checkbox');conflict.input.required=true;conflict.wrap.className='check';form.append(conflict.wrap);}const submit=el('button','确认并开始跟进');form.append(submit);form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{await api(`/tasks/${t.id}/confirm`,{version:t.version,owner:owner.input.value,due_date:due.input.value||null,note:note.input.value,conflict_ids:conflict?.input.checked?source.message_id_conflicts:[]});await refresh(source.id);notice('任务已确认，进入待处理。');}catch(e){notice(e.message,true);}finally{submit.disabled=false;}});card.append(form);}
 const transitions={draft:['rejected'],rejected:[],open:['doing','blocked','done','cancelled'],doing:['open','blocked','done','cancelled'],blocked:['open','doing','cancelled'],done:['open'],cancelled:['open']};
 if(transitions[t.state].length){const d=el('details');d.append(el('summary','变更状态 / 退回候选'));const note=field('变更原因（至少5字）','textarea');note.input.maxLength=1000;d.append(note.wrap);const row=el('div',undefined,'actions');transitions[t.state].forEach(state=>row.append(button(names[state],async()=>{if(note.input.value.trim().length<5)throw Error('请填写至少5字的变更原因');await api(`/tasks/${t.id}/state`,{version:t.version,state,note:note.input.value});await refresh(source.id);notice('状态变化已记录。');})));d.append(row);card.append(d);}
 const history=el('details'),records=el('div');history.append(el('summary','任务历史与确认依据'),button('读取历史',async()=>{const rows=await api(`/tasks/${t.id}/history`);records.replaceChildren(...rows.map(r=>{const d=el('details');d.append(el('summary',`v${r.snapshot.version} · ${names[r.snapshot.state]} · ${r.note}`),el('pre',JSON.stringify(r.snapshot,null,2)));return d;}));}),records);card.append(history);$('#tasks').append(card);}
async function exportsList(){const rows=await api('/exports');$('#exports').replaceChildren(...rows.map(r=>button('下载 '+new Date(r.created_at).toLocaleString(),async()=>{const data=await api('/exports/'+r.id);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=`inbox-tasks-${r.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})));if(!rows.length)$('#exports').append(el('p','暂无快照，先确认至少一项任务。','muted'));}
$('#candidate').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const mid=selected?.id;try{if(!mid)throw Error('请先选择邮件');const f=e.target.elements,data={title:f.title.value,quote:f.quote.value,quote_start:f.quote_start.value===''?null:Number(f.quote_start.value)};if(editing)await api('/tasks/'+editing.id+'/revise',{...data,version:editing.version,note:f.note.value});else await api('/messages/'+mid+'/tasks',data);await refresh(mid);notice('已保存，候选仍需人工确认。');}catch(e){notice(e.message,true);}finally{b.disabled=false;}});
$('#cancel-edit').onclick=reset;$('#token').onclick=()=>{const token=prompt('工作台访问令牌（仅保存在本标签页）');if(token!==null){sessionStorage.setItem('it-token',token);location.reload();}};
$('#upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('邮件超过2MB');const r=await api('/messages',await file.arrayBuffer(),true);await load(r.id);notice(r.duplicate?'已存在该邮件，打开原记录。':'邮件已导入，原文保存在本机。');}catch(e){notice(e.message,true);}finally{e.target.value='';}};
action($('#sample'),async()=>{const response=await fetch('/sample.eml');if(!response.ok)throw Error('合成样例加载失败');const r=await api('/messages',await response.arrayBuffer(),true);await load(r.id);notice('已打开合成示例，可核对已有任务或继续创建候选。');});
action($('#generate'),async()=>{const mid=selected?.id;if(!mid)throw Error('请先选择邮件');notice('免费模型处理中…候选仍需核对。');const r=await api('/messages/'+mid+'/suggest',{});await refresh(mid);notice(r.tasks.length?`返回${r.tasks.length}项候选（可能包含已有条目）。请核对否定、改期及旧引用。`:'模型没有提取出候选，不代表没有任务。请检查原文，必要时手工补充。');});
action($('#export'),async()=>{const r=await api('/exports',{});await exportsList();notice(`已冻结${r.tasks.length}项已确认任务，快照包含来源邮件。`);});
(async()=>{try{const status=await api('/status');configured=status.model_configured;$('#model-status').textContent=configured?'免费模型已配置 · 候选需审核':'模型未配置 · 手工流程可用';await Promise.all([list(),exportsList()]);}catch(e){notice(e.message,true);}})();
