const $ = s => document.querySelector(s);
let selected = null, evidence = [];
const labels = {saved:'已收藏',applied:'已投递',screening:'初筛',interview:'面试',offer:'收到 Offer',rejected:'未通过',withdrawn:'已撤回',accepted:'已接受'};
const transitions = {saved:['applied','withdrawn'],applied:['screening','interview','rejected','withdrawn'],screening:['interview','rejected','withdrawn'],interview:['offer','rejected','withdrawn'],offer:['accepted','withdrawn'],rejected:['saved'],withdrawn:['saved'],accepted:[]};
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function note(text){$('#status').textContent=text;}
async function api(path,data){const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+$('#token').value},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok){const e=await r.json();throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail));}return r.json();}
function button(text,action){const b=el('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await action();}catch(e){note(e.message);}finally{b.disabled=false;}};return b;}
function field(form,name,title,type='text',value='',options=[]){const l=el('label',title);const n=el(type==='textarea'?'textarea':type==='select'?'select':'input');n.name=name;if(type==='select'){for(const [v,t] of options){const o=el('option',t);o.value=v;n.append(o);}}else if(type!=='textarea')n.type=type;n.value=value;l.append(n);form.append(l);return n;}
function form(parent,title,action){const f=el('form');f.append(el('h3',title));f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button[type=submit]');b.disabled=true;try{await action(Object.fromEntries(new FormData(f)));}catch(err){note(err.message);}finally{b.disabled=false;}};parent.append(f);return f;}
function submit(f,text){const b=el('button',text);b.type='submit';f.append(b);}
function kind(f,value='required'){return field(f,'kind','要求类型','select',value,[['responsibility','职责'],['required','必须'],['preferred','优先']]);}
async function refresh(){const h=await api('/health');evidence=await api('/evidence');$('#evidence').replaceChildren(...evidence.map(e=>el('p',e.title+'：'+e.body)));const jobs=await api('/jobs');$('#jobs').replaceChildren(...jobs.map(j=>button(j.company+' · '+j.title+' / '+labels[j.stage],()=>open(j.id))));note(h.model_configured?'已连接 · 免费模型已配置，候选仍需审核':'已连接 · 未配置模型，可手工录入');if(selected)await open(selected);}
async function open(id){selected=id;const j=await api('/jobs/'+id);const root=$('#workspace');root.replaceChildren(el('h2',j.company+' · '+j.title),el('p','阶段：'+labels[j.stage]+' / 版本 '+j.version));const original=el('details');original.append(el('summary','查看岗位原文与哈希'),el('pre',j.jd),el('p',j.sha256));root.append(original);
 root.append(el('p','模型最多读取 '+Math.min(j.jd.length,4000)+' 字符；'+(j.jd.length>4000?'其余内容请手工补充。':'当前原文在处理范围内。')));
 root.append(button('免费模型提取要求',async()=>{note('正在提取，请等待；不会自动审核。');await api('/jobs/'+id+'/extract',{});await open(id);note('提取完成，请逐条核对原文和限定。');}));
 const manual=form(root,'手工补充岗位要求',async d=>{await api('/jobs/'+id+'/requirements',d);await open(id);});field(manual,'label','要求简述');field(manual,'quote','连续逐字原文','textarea');kind(manual);submit(manual,'添加待审核要求');
 root.append(el('h3','要求与证据'),el('p','已审核 '+j.coverage.approved_requirements+' 条，已关联证据 '+j.coverage.linked_requirements+' 条。关联覆盖不是胜任度或录用概率。'));
 for(const r of j.requirements){const card=el('article');card.append(el('h3',r.label+' · '+r.status),el('blockquote',r.quote));root.append(card);if(r.status==='draft'){const f=form(card,'核对与审核',async d=>{await api('/requirements/'+r.id+'/review',{...d,version:r.version});await open(id);});field(f,'label','修订简述','text',r.label);kind(f,r.kind);field(f,'decision','审核决定','select','approved',[['approved','确认要求'],['rejected','排除错误候选']]);field(f,'note','核对说明（至少5字）','textarea');submit(f,'保存审核');}
 if(r.status==='approved'){card.append(el('p',r.evidence.length?'已关联证据：':'尚无证据，保留能力缺口。'));for(const m of r.evidence)card.append(el('p',m.title+'：'+m.quote+' / '+m.rationale));if(evidence.length){const f=form(card,'关联已有项目证据',async d=>{await api('/requirements/'+r.id+'/evidence',d);await open(id);});field(f,'evidence_id','选择证据','select',evidence[0].id,evidence.map(e=>[e.id,e.title]));field(f,'quote','证据正文的连续逐字片段','textarea');field(f,'rationale','为什么能支撑该要求（至少5字）','textarea');submit(f,'关联证据');}const correction=form(card,'撤回错误要求',async d=>{await api('/requirements/'+r.id+'/withdraw',{...d,version:r.version});await open(id);});field(correction,'note','撤回原因（保留历史快照）','textarea');submit(correction,'撤回已审核要求');}}
 root.append(button('冻结当前审核材料（含缺口）',async()=>{await api('/jobs/'+id+'/packets',{});await open(id);note('材料快照已冻结，不会随之后的编辑改变。');}));
 for(const p of j.packets)root.append(button('导出材料 '+p.created_at,async()=>{const body=await api('/packets/'+p.id+'/export');const url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='applytrack-packet.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));
 if(transitions[j.stage].length){const f=form(root,'记录投递或面试进度',async d=>{await api('/jobs/'+id+'/stage',{...d,version:j.version});await refresh();});field(f,'stage','下一阶段','select',transitions[j.stage][0],transitions[j.stage].map(s=>[s,labels[s]]));field(f,'packet_id','投递时所用材料（投递必选）','select','',[['','请选择'],...j.packets.map(p=>[p.id,p.created_at])]);field(f,'note','进度记录／面试复盘（至少5字）','textarea');submit(f,'记录阶段变更');}
 const follow=form(root,'下次跟进日期',async d=>{await api('/jobs/'+id+'/follow-up',{...d,due:d.due||null,version:j.version});await refresh();});field(follow,'due','日期（留空取消）','date',j.follow_up);field(follow,'note','跟进计划（至少5字）','textarea');submit(follow,'保存跟进计划');
 const logs=el('details');logs.append(el('summary','审计与模型运行记录'));for(const e of j.events)logs.append(el('p',e.created_at+' '+e.kind+' '+e.detail));for(const r of j.runs)logs.append(el('pre',r.state+' '+r.trace));root.append(logs);
}
for(const [id,path] of [['new-job','/jobs'],['new-evidence','/evidence']]){$('#'+id).onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{const result=await api(path,Object.fromEntries(new FormData(f)));f.reset();if(path==='/jobs')selected=result.id;await refresh();}catch(err){note(err.message);}finally{b.disabled=false;}};}
$('#token').value=sessionStorage.getItem('applytrack-token')||'';
$('#connect').onclick=()=>{sessionStorage.setItem('applytrack-token',$('#token').value);refresh().catch(e=>note(e.message));};
refresh().catch(e=>note(e.message));
