'use strict';
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const names={starting:'正在启动',running:'正在运行',finished:'执行完成',failed:'执行失败',interrupted:'执行中断',execution_unknown:'进程状态待核查'};
let busy=false,requestKey=crypto.randomUUID(),polling=false;const retryKeys=new Map();let diagnosticId=null;
async function api(url,options){const r=await fetch(url,options),data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function lock(value){busy=value;document.querySelectorAll('select,button').forEach(n=>n.disabled=value);}
async function versions(){const sid=$('job-suite').value;$('job-version').replaceChildren();if(!sid){$('job-plan').textContent='请先在测试集工作室保存一个版本。';return;}const rows=await api(`/api/suites/${sid}/versions`);for(const r of rows){const o=el('option',`v${r.version} · ${r.note}`);o.value=r.version;$('job-version').append(o);}await plan();}
async function plan(){requestKey=crypto.randomUUID();const sid=$('job-suite').value,v=$('job-version').value;if(!sid||!v)return;const r=await api(`/api/suites/${sid}/versions/${v}`);$('job-plan').textContent=`${r.suite.cases.length} 个样例 × ${r.suite.prompts.length} 套提示词 = ${r.suite.cases.length*r.suite.prompts.length} 次本地调用 · SHA-256 ${r.sha256}`;}
async function refresh(){if(polling)return;polling=true;try{const rows=await api('/api/jobs');$('job-list').replaceChildren();if(!rows.length)$('job-list').append(el('p','还没有任务。选择测试集和版本后开始运行。'));for(const r of rows){const card=el('article');card.className='case-edit';card.append(el('h4',`${r.name} · v${r.suite_version} · ${names[r.state]||r.state}`),el('p',`${r.planned_calls} 次计划调用 · ${r.created_at}`));const id=el('p',`任务 ${r.id} · 测试集 SHA-256 ${r.suite_sha256}`);id.className='provenance';card.append(id);if(r.error)card.append(el('pre',r.error));if(r.run_id){const link=el('a','进入本次结果复核 →');link.href='/?run='+r.run_id;card.append(link);}if(['failed','interrupted'].includes(r.state)){const b=el('button','以相同版本新建重试任务');b.type='button';b.disabled=busy;b.addEventListener('click',async()=>{if(!retryKeys.has(r.id))retryKeys.set(r.id,crypto.randomUUID());if(await start(r.suite_id,r.suite_version,retryKeys.get(r.id)))retryKeys.delete(r.id);});card.append(b);}const diagnose=el('button','查看诊断');diagnose.type='button';diagnose.className='secondary';diagnose.disabled=busy;diagnose.addEventListener('click',()=>diagnostics(r.id));card.append(diagnose);if(r.completed_at)card.append(el('p','记录完成时间：'+r.completed_at));$('job-list').append(card);}}catch(e){$('message').textContent=e.message;}finally{polling=false;}}
async function start(suite_id,version,key){if(busy)return;lock(true);try{const job=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({suite_id,version:Number(version),request_key:key})});requestKey=crypto.randomUUID();$('message').textContent=`任务已记录：${names[job.state]||job.state}。结果会自动导入，页面每两秒刷新状态。`;await refresh();return true;}catch(e){$('message').textContent=e.message+'（如为网络错误，再次提交将复用当前请求标识。）';return false;}finally{lock(false);}}
$('job-form').addEventListener('submit',e=>{e.preventDefault();start($('job-suite').value,$('job-version').value,requestKey);});
$('job-suite').addEventListener('change',async()=>{lock(true);try{await versions();}catch(e){$('message').textContent=e.message;}finally{lock(false);}});
$('job-version').addEventListener('change',async()=>{lock(true);try{await plan();}catch(e){$('message').textContent=e.message;}finally{lock(false);}});
$('refresh-jobs').addEventListener('click',refresh);
async function diagnostics(id){if(busy)return;lock(true);try{await showDiagnostics(id);}catch(e){$('message').textContent=e.message;}finally{lock(false);}}
async function showDiagnostics(id){const d=await api('/api/jobs/'+id+'/diagnostics');diagnosticId=id;const state=x=>x===true?'仍在运行':x===false?'已退出或身份不匹配':'无法核实';const box=$('diagnostic-content');box.replaceChildren(el('p',`任务 ${id} · ${names[d.job.state]}`),el('p',`工作进程：${state(d.worker_alive)}；引擎进程：${state(d.engine_alive)}`));if(d.job.error)box.append(el('pre',d.job.error));for(const [label,key] of [['执行器日志','worker_log'],['评测引擎日志','engine_log']]){box.append(el('h4',label+(d[key].truncated?'（仅末尾 16KB）':'')),el('pre',d[key].present?d[key].text:'尚无日志文件'));}box.append(el('h4','恢复历史'));for(const event of d.events)box.append(el('pre',`${event.created_at}\n${event.detail}`));if(!d.events.length)box.append(el('p','尚无恢复操作。'));$('recover-job').hidden=!['failed','interrupted','execution_unknown'].includes(d.job.state)||Boolean(d.job.run_id);$('diagnostics').hidden=false;}
$('recover-job').addEventListener('click',async()=>{if(busy||!diagnosticId)return;lock(true);try{await api('/api/jobs/'+diagnosticId+'/recover',{method:'POST'});await showDiagnostics(diagnosticId);await refresh();$('message').textContent='已有结果已恢复导入，未重新调用模型；原失败原因保留在恢复历史中。';}catch(e){$('message').textContent=e.message;}finally{lock(false);}});
async function init(){lock(true);try{for(const r of await api('/api/suites')){const o=el('option',r.suite.name);o.value=r.suite_id;$('job-suite').append(o);}await versions();await refresh();}catch(e){$('message').textContent=e.message;}finally{lock(false);}}
init();setInterval(refresh,2000);
