'use strict';
const $=id=>document.getElementById(id);
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let record=null,baseline='',busy=false,seed=null,draftSource=null;
async function api(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function message(text){$('message').textContent=text;}
function lock(value){busy=value;document.querySelectorAll('input,textarea,select,button').forEach(n=>n.disabled=value);}
function control(parent,label,tag,value,max){const wrapper=el('label',label),input=el(tag);input.value=value||'';input.required=true;if(max)input.maxLength=max;wrapper.append(input);parent.append(wrapper);return input;}
function button(parent,text,action){const b=el('button',text);b.type='button';b.className='secondary small-button';b.addEventListener('click',action);parent.append(b);return b;}
function promptCard(p){const card=el('section');card.className='prompt-edit';const top=el('div');top.className='editor-top';const id=control(top,'提示词标识','input',p.id,60);id.className='prompt-id';button(top,'移除',()=>{if($('prompt-editor').children.length<=2){message('至少保留两套提示词。');return;}card.remove();});card.append(top);const instruction=control(card,'指令内容','textarea',p.instruction,6000);instruction.className='instruction';$('prompt-editor').append(card);}
function checkRow(parent,c){const row=el('div');row.className='check-row';const select=control(row,'检查规则','select','');select.required=true;for(const [value,label] of [['equals','完全等于'],['contains','包含文本'],['not-contains','不含文本'],['is-json','有效 JSON']]){const o=el('option',label);o.value=value;select.append(o);}select.value=c.type;const input=control(row,'期望文本','input',c.value,2000);input.className='check-value';function update(){input.parentElement.hidden=select.value==='is-json';input.required=select.value!=='is-json';}select.addEventListener('change',update);update();button(row,'移除规则',()=>{if(parent.children.length<=1){message('每个样例至少需要一条自动检查。');return;}row.remove();});parent.append(row);}
function caseCard(c){const card=el('section');card.className='case-edit';const top=el('div');top.className='editor-top';control(top,'样例标识','input',c.id,60).className='case-id';button(top,'移除样例',()=>{if($('case-editor').children.length<=1){message('至少保留一个样例。');return;}card.remove();});card.append(top);control(card,'输入内容','textarea',c.input,8000).className='case-input';control(card,'人工复核判据','textarea',c.rubric,2000).className='rubric';const checks=el('div');checks.className='checks';for(const c1 of c.checks)checkRow(checks,c1);card.append(checks);button(card,'添加检查规则',()=>{if(checks.children.length>=8){message('每个样例最多八条自动检查。');return;}checkRow(checks,{type:'equals',value:''});});$('case-editor').append(card);}
function value(){return {name:$('suite-name').value,prompts:[...document.querySelectorAll('.prompt-edit')].map(p=>({id:p.querySelector('.prompt-id').value,instruction:p.querySelector('.instruction').value})),cases:[...document.querySelectorAll('.case-edit')].map(c=>({id:c.querySelector('.case-id').value,input:c.querySelector('.case-input').value,rubric:c.querySelector('.rubric').value,checks:[...c.querySelectorAll('.check-row')].map(row=>{const type=row.querySelector('select').value;return type==='is-json'?{type}:{type,value:row.querySelector('.check-value').value};})}))};}
function state(){return JSON.stringify({suite:value(),note:$('change-note').value});}
function dirty(){return baseline&&state()!==baseline;}
function mayLeave(){if(!dirty())return true;message('有未保存的修改。请先保存，或明确丢弃后再切换测试集。');$('discard-draft').hidden=false;return false;}
function render(suite){draftSource=structuredClone(suite);$('suite-name').value=suite.name;$('prompt-editor').replaceChildren();$('case-editor').replaceChildren();suite.prompts.forEach(promptCard);suite.cases.forEach(caseCard);$('change-note').value='';$('discard-draft').hidden=true;$('version-info').textContent=record?`版本 ${record.version} · ${record.created_at} · SHA-256 ${record.sha256}`:'尚未保存 · 从当前内容创建新测试集';$('save-help').textContent=record?`保存后创建版本 ${record.version+1}，旧版本保留`:'首次保存会创建独立测试集';baseline=state();}
async function history(){ $('suite-history').replaceChildren();$('version-preview').replaceChildren();if(!record)return;const id=record.suite_id;const rows=await api(`/api/suites/${id}/versions`);for(const item of rows){const row=el('div');row.className='history-row';row.append(el('b',`v${item.version}`),el('p',`${item.note} · ${item.created_at}`));const link=el('a','下载此版本');link.href=`/api/suites/${id}/versions/${item.version}/download`;row.append(link);button(row,'查看快照',async()=>{if(busy)return;lock(true);try{const old=await api(`/api/suites/${id}/versions/${item.version}`);const preview=$('version-preview');preview.replaceChildren(el('h4',`${old.suite.name} · v${old.version}（只读）`),el('p',old.note));for(const p of old.suite.prompts)preview.append(el('h4',p.id),el('pre',p.instruction));for(const c of old.suite.cases)preview.append(el('h4',c.id),el('pre',`${c.input}\n\n业务判据：${c.rubric}\n检查：${c.checks.map(x=>x.type+(x.value?' '+x.value:'')).join('；')}`));}catch(e){message(e.message);}finally{lock(false);}});$('suite-history').append(row);}}
async function list(selected=''){const rows=await api('/api/suites');$('suite-picker').replaceChildren();const blank=el('option','新建测试集');blank.value='';$('suite-picker').append(blank);for(const row of rows){const o=el('option',`${row.suite.name} · v${row.version}`);o.value=row.suite_id;$('suite-picker').append(o);}$('suite-picker').value=selected;return rows;}
$('add-prompt').addEventListener('click',()=>{if($('prompt-editor').children.length>=3){message('最多比较三套提示词。');return;}promptCard({id:'',instruction:''});});
$('add-case').addEventListener('click',()=>{if($('case-editor').children.length>=20){message('最多二十个样例。');return;}caseCard({id:'',input:'',rubric:'',checks:[{type:'equals',value:''}]});});
$('discard-draft').addEventListener('click',()=>{if(!busy){render(record?record.suite:draftSource);message('未保存修改已丢弃。');}});
$('new-suite').addEventListener('click',()=>{if(busy||!mayLeave())return;record=null;$('suite-picker').value='';render(seed);history();message('已载入工单示例，保存后才会创建新测试集。');});
$('reload-suite').addEventListener('click',async()=>{if(busy||!mayLeave())return;lock(true);try{const id=record?.suite_id||'';const rows=await list(id);record=rows.find(r=>r.suite_id===id)||null;render(record?record.suite:seed);await history();message('已重新载入最新保存版本。');}catch(e){message(e.message);}finally{lock(false);}});
$('suite-picker').addEventListener('change',async()=>{if(busy)return;if(!mayLeave()){$('suite-picker').value=record?.suite_id||'';return;}const id=$('suite-picker').value;lock(true);try{if(!id){record=null;render(seed);}else{const rows=await list(id);record=rows.find(r=>r.suite_id===id);if(!record)throw Error('测试集已不可用');render(record.suite);}await history();message('');}catch(e){message(e.message);}finally{lock(false);}});
$('copy-run').addEventListener('click',async()=>{if(busy||!mayLeave())return;const id=$('run-source').value;if(!id){message('先选择一条评测记录。');return;}lock(true);try{const run=await api('/api/runs/'+id);record=null;$('suite-picker').value='';render(run.suite);await history();message('已复制历史运行使用的测试集。保存将新建记录，原评测不变。');}catch(e){message(e.message);}finally{lock(false);}});
$('suite-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const payload={suite:value(),note:$('change-note').value};if(record)payload.version=record.version;lock(true);try{const saved=await api(record?'/api/suites/'+record.suite_id:'/api/suites',{method:record?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});record=saved;render(saved.suite);await list(saved.suite_id);await history();message(`测试集版本 ${saved.version} 已保存。历史运行和报告未被修改。`);}catch(e){message(e.message+'；当前草稿已保留。');}finally{lock(false);}});
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
async function init(){lock(true);try{seed=await api('/api/suite-sample');await list();render(seed);const runs=await api('/api/runs');for(const run of runs){const o=el('option',`${run.name} · ${run.id.slice(0,8)}`);o.value=run.id;$('run-source').append(o);}}catch(e){message(e.message);}finally{lock(false);}}
init();
