const {test}=require('node:test'),assert=require('node:assert/strict');
const never=()=>new Promise(()=>{});
const tick=()=>new Promise(r=>setImmediate(r));
function fake(){return {terminated:0,setParameters:async()=>{},recognize:async()=>({data:{text:'真实输出'}}),async terminate(){this.terminated++;}};}
test('successful OCR returns engine output and releases worker',async()=>{const {runOCR}=await import('../ocr-job.mjs');const w=fake();assert.equal((await runOCR({createWorker:async()=>w,image:{}})).data.text,'真实输出');assert.equal(w.terminated,1);});
test('cancel during parameter preparation does not hang or start recognition',async()=>{const {runOCR}=await import('../ocr-job.mjs');const w=fake(),c=new AbortController();w.setParameters=never;w.recognize=()=>assert.fail('recognize must not start');const run=runOCR({createWorker:async()=>w,signal:c.signal});await tick();c.abort();await assert.rejects(run,/取消/);assert.equal(w.terminated,1);});
test('cancel during recognition releases worker exactly once',async()=>{const {runOCR}=await import('../ocr-job.mjs');const w=fake(),c=new AbortController();w.recognize=never;const run=runOCR({createWorker:async()=>w,signal:c.signal});await tick();c.abort();await assert.rejects(run,/取消/);assert.equal(w.terminated,1);});
test('timeout covers hung parameter preparation',async()=>{const {runOCR}=await import('../ocr-job.mjs');const w=fake();w.setParameters=never;await assert.rejects(runOCR({createWorker:async()=>w,timeoutMs:10}),/超过/);assert.equal(w.terminated,1);});
test('late initialization after timeout is disposed; progress ignored',async()=>{const {runOCR}=await import('../ocr-job.mjs');let resolve,options;const w=fake(),progress=[];const run=runOCR({createWorker:o=>{options=o;return new Promise(r=>resolve=r);},timeoutMs:10,onProgress:p=>progress.push(p)});await assert.rejects(run,/超过/);resolve(w);options.logger('late');await tick();assert.equal(w.terminated,1);assert.deepEqual(progress,[]);});
test('initialization error callback rejects even when factory remains pending',async()=>{const {runOCR}=await import('../ocr-job.mjs');await assert.rejects(runOCR({createWorker:({errorHandler})=>{queueMicrotask(()=>errorHandler('model not found'));return never();}}),/model not found/);});
