const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),path=require('node:path');
const recipes=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/recipes.json'),'utf8')).recipes;
const settings={inventory:['西红柿','鸡蛋','食用油','盐'],excluded:[],tools:['炒锅','汤锅','菜刀与碗'],maxTime:30,includeOptional:false,factor:2};
test('ingredient aliases and duplicate stock names normalize',async()=>{const {tokens}=await import('../pantry-core.mjs');assert.deepEqual(tokens('番茄，西红柿、油\n盐'),['西红柿','食用油','盐']);});
test('recipe formulas retain offsets, ranges and egg rounding',async()=>{const {amounts}=await import('../pantry-core.mjs');const tomato=recipes.find(r=>r.id==='tomato-eggs');assert.equal(amounts(tomato.ingredients.find(i=>i.name==='鸡蛋'),1,tomato).min,2);assert.equal(amounts(tomato.ingredients.find(i=>i.name==='食用油'),2,tomato).min,12);const cucumber=recipes.find(r=>r.id==='cucumber');assert.equal(amounts(cucumber.ingredients.find(i=>i.name==='醋'),2,cucumber).min,15.5);assert.throws(()=>amounts(tomato.ingredients[0],0,tomato));});
test('hard constraints exclude optional allergens before model ranking',async()=>{const {inspectRecipe,rankRecipes}=await import('../pantry-core.mjs');const soup=recipes.find(r=>r.id==='seaweed-soup');const row=inspectRecipe(soup,{...settings,excluded:['甲壳类']});assert.ok(row.reasons.some(x=>x.includes('甲壳类')));assert.equal(rankRecipes([row],[{id:soup.id,score:1}]).length,0);const tofu=recipes.find(r=>r.id==='tofu');assert.ok(inspectRecipe(tofu,{...settings,maxTime:15}).reasons.length===2);});
test('shopping merges same units but never converts grams to milliliters',async()=>{const {shoppingList}=await import('../pantry-core.mjs');const rows=shoppingList(recipes.filter(r=>['tomato-eggs','tomato-noodles'].includes(r.id)),{...settings,inventory:[]});assert.equal(rows.filter(r=>r.name==='食用油').length,2);assert.equal(rows.find(r=>r.name==='鸡蛋').min,5);assert.ok(rows.find(r=>r.name==='葱').unknown);assert.ok(!rows.some(r=>r.name==='糖'));});
test('source snapshots match the pinned upstream hashes',()=>{for(const r of recipes){const raw=fs.readFileSync(path.join(__dirname,'..',r.sourceFile));assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),r.sourceSha256);assert.ok(r.ingredients.length&&r.instructions&&r.source.includes('a2d45c6984dff9ee941da0e7c452f7965965d962'));}});
test('missing model scores are errors, not silent fallback recommendations',async()=>{const {inspectRecipe,rankRecipes}=await import('../pantry-core.mjs');const row=inspectRecipe(recipes[0],settings);assert.throws(()=>rankRecipes([row],[]));});
