const $=s=>document.querySelector(s), labels={problem:'问题',request:'建议',praise:'表扬',other:'其他'},states={draft:'待审核',confirmed:'已确认',rejected:'已拒绝'};
let sources=[],annotations=[],duplicates=[],selected=null,busy=false;
function el(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
async function api(path,data,raw=false){const r=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':raw?'text/csv':'application/json'},body:raw?data:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'输入不符合要求');return value;}
async function act(fn){if(busy)return;busy=true;try{const message=await fn();await load();$('#notice').textContent=typeof message==='string'?message:'已保存。';}catch(e){$('#notice').textContent=e.message;}finally{busy=false;}}
function fields(form){return Object.fromEntries(new FormData(form));}
async function load(){[sources,annotations,duplicates]=await Promise.all([api('feedback'),api('annotations'),api('duplicates')]);renderSources();if(selected)await choose(selected);await listReports();}
function renderSources(){const query=$('#search').value.trim().toLowerCase();$('#sources').replaceChildren();for(const s of sources.filter(x=>(x.text+x.channel+x.source_id).toLowerCase().includes(query))){const b=el('button',s.source_id+' · '+s.channel+' / '+s.text);b.onclick=()=>choose(s.source_id).catch(e=>$('#notice').textContent=e.message);$('#sources').append(b);}}
async function choose(id){selected=id;const source=sources.find(x=>x.source_id===id);$('#selected').textContent=id+' · '+source.channel;$('#original').textContent=source.text;$('#suggest').disabled=false;renderAnnotations();renderDuplicate();$('#similar').replaceChildren();const candidates=await api('similar?source_id='+encodeURIComponent(id));if(selected!==id)return;for(const c of candidates)$('#similar').append(el('p',c.source_id+' · '+c.character_similarity+' / '+c.text));}
function renderDuplicate(){
 const box=$('#duplicate');box.replaceChildren();const current=duplicates.find(d=>d.source_id===selected);
 box.append(el('h3','人工重复判断'),el('p','仅在确认同一反馈被重复收录时标记。相似意见可能来自不同人；标记不会删除原文或归类。'));
 const form=el('form',''),label=el('label','代表反馈'),select=el('select','');select.name='target_id';
 const none=el('option','独立保留（或撤销重复标记）');none.value='';select.append(none);
 for(const source of sources.filter(s=>s.source_id!==selected)){const option=el('option',source.source_id+' / '+source.text);option.value=source.source_id;select.append(option);}
 select.value=current?.target_id||'';label.append(select);form.append(label);
 const noteLabel=el('label','判断原因（至少5字）'),note=el('textarea','');note.name='note';note.required=true;note.minLength=5;note.maxLength=1000;noteLabel.append(note);form.append(noteLabel,el('button','保存重复判断'));
 form.onsubmit=e=>{e.preventDefault();act(()=>api('duplicates',{...fields(form),source_id:selected,target_id:select.value||null,version:current?.version||0}));};box.append(form);
 const history=el('button','查看重复判断历史');history.type='button';history.onclick=async()=>{try{const rows=await api('duplicates/'+encodeURIComponent(selected)+'/history');let pre=box.querySelector('pre');if(!pre){pre=el('pre','');box.append(pre);}pre.textContent=JSON.stringify(rows,null,2);}catch(e){$('#notice').textContent=e.message;}};box.append(history);
}
function editor(form,a){for(const [key,title] of [['theme','主题'],['kind','类型'],['quote','原文引用'],['note','审核或修订原因（至少5字）']]){const label=el('label',title),input=document.createElement(key==='kind'?'select':key==='quote'||key==='note'?'textarea':'input');input.name=key;input.required=true;if(key==='kind'){for(const [v,t] of Object.entries(labels)){const o=el('option',t);o.value=v;input.append(o);}}else{input.minLength=key==='note'?5:2;input.maxLength=key==='theme'?100:key==='note'?1000:4000;}input.value=a[key]||'';label.append(input);form.append(label);}}
function renderAnnotations(){$('#annotations').replaceChildren();for(const a of annotations.filter(x=>x.source_id===selected)){const form=el('form','');form.className='card';form.append(el('h3',states[a.state]+' · 版本 '+a.version));editor(form,a);const save=el('button','保存修订（重新审核）');form.append(save);form.onsubmit=e=>{e.preventDefault();act(()=>api('annotations/'+a.id+'/revise',{...fields(form),version:a.version}));};for(const [decision,title] of [['confirmed','确认当前版本'],['rejected','拒绝当前版本']]){const b=el('button',title);b.type='button';b.disabled=a.state===decision;b.onclick=()=>act(async()=>{const values=fields(form);if(['theme','kind','quote'].some(k=>values[k]!==a[k]))throw Error('内容已修改，请先保存修订，再审核新版本');if(values.note.trim().length<5)throw Error('请填写至少5字审核原因');await api('annotations/'+a.id+'/review',{version:a.version,decision,note:values.note});});form.append(b);}const history=el('button','查看历史');history.type='button';history.onclick=async()=>{try{const data=await api('annotations/'+a.id+'/history');let pre=form.querySelector('pre');if(!pre){pre=el('pre','');form.append(pre);}pre.textContent=JSON.stringify(data,null,2);}catch(e){$('#notice').textContent=e.message;}};form.append(history);$('#annotations').append(form);}if(!$('#annotations').children.length)$('#annotations').append(el('p','暂无归类，可手工添加或请求模型建议。'));}
$('#search').oninput=renderSources;
$('#import').onsubmit=e=>{e.preventDefault();act(async()=>{const file=$('#file').files[0];if(file.size>1000000)throw Error('文件超过1MB');const result=await api('imports',await file.arrayBuffer(),true);return `导入完成：新增 ${result.added} 条，复用 ${result.reused} 条。${result.same_file?'同一文件已导入，未重复计数。':''}`;});};
$('#manual').onsubmit=e=>{e.preventDefault();act(async()=>{if(!selected)throw Error('先选择一条反馈');await api('annotations',{...fields(e.target),source_id:selected});e.target.reset();});};
$('#suggest').onclick=()=>act(async()=>{const id=selected;if(!id)throw Error('先选择反馈');$('#notice').textContent='本地模型处理中…';await api('suggestions',{source_id:id});});
async function runs(){const rows=await api('model-runs');$('#run-list').replaceChildren();for(const r of rows){const box=el('article','');box.append(el('h3',r.source_id+' · '+(r.status==='saved'?'草稿已保存':'失败')),el('p',r.error||'必须人工核对主题和原文'));const metadata=JSON.parse(r.metadata||'{}');box.append(el('p',metadata.prompt_version?`${metadata.model} · 提示词 ${metadata.prompt_version} · SHA256 ${metadata.prompt_sha256}`:'历史记录未保存模型与提示词版本。'));const details=el('details','');details.append(el('summary','查看原始输出'),el('pre',r.raw||'没有模型输出'));box.append(details);$('#run-list').append(box);}}
$('#reload-runs').onclick=()=>runs().catch(e=>$('#notice').textContent=e.message);
async function showReport(id){const r=await api('reports/'+id);const box=$('#report-view');box.hidden=false;box.replaceChildren(el('h2',r.title),el('p',r.review_note),el('p',`反馈总数 ${r.total_feedback} · 已确认反馈 ${r.confirmed_feedback}`));box.append(el('p',r.deduplicated_total_feedback===undefined?'旧版报告未记录人工重复判断。':`人工去重后总数 ${r.deduplicated_total_feedback} · 已确认 ${r.deduplicated_confirmed_feedback}；均为反馈记录口径，不是人数。`));for(const t of r.themes)box.append(el('p',t.theme+'：'+t.feedback_count+' 条（'+t.source_ids.join(', ')+'）'+(t.deduplicated_feedback_count===undefined?'':'；人工去重后 '+t.deduplicated_feedback_count+' 条')));const evidence=el('details','');evidence.append(el('summary','查看冻结证据'),el('pre',JSON.stringify({evidence:r.evidence,duplicate_decisions:r.duplicate_decisions,counting_rule:r.counting_rule},null,2)));box.append(evidence);const b=el('button','导出报告 JSON');b.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const a=el('a','');a.href=url;a.download='feedback-report-'+id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};box.append(b);}
async function listReports(){const rows=await api('reports');$('#report-list').replaceChildren();for(const r of rows){const b=el('button',r.title+' · '+new Date(r.created_at).toLocaleString());b.onclick=()=>showReport(r.id).catch(e=>$('#notice').textContent=e.message);$('#report-list').append(b);}}
$('#freeze').onsubmit=e=>{e.preventDefault();act(async()=>{const r=await api('reports',fields(e.target));await showReport(r.id);});};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{for(const id of ['work','runs','reports'])$('#'+id).hidden=id!==b.dataset.tab;if(b.dataset.tab==='runs')runs().catch(e=>$('#notice').textContent=e.message);});
load().then(async()=>{$('#notice').textContent=(await api('status')).model_configured?'免费本地模型已连接；建议需审核。':'模型未配置，手工归类可用。';}).catch(e=>$('#notice').textContent=e.message);
