const $=s=>document.querySelector(s);let selected=null,busy=false,current=null;
const labels={equal:'未改变',replace:'替换',insert:'新增',delete:'删除'};
function el(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
async function api(path,data){const r=await fetch('/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'输入不符合要求');return value;}
function dirty(){return [...$('#version').querySelectorAll('input,textarea')].some(x=>x.value.length>0)||reviewDirty();}
async function act(fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('input,textarea,select,button')].map(node=>[node,node.disabled]);for(const [node] of controls)node.disabled=true;try{await fn();$('#notice').textContent='操作完成。';}catch(e){$('#notice').textContent=e.message;}finally{for(const [node,disabled] of controls)if(node.isConnected)node.disabled=disabled;busy=false;}}
async function documents(){const rows=await api('documents');$('#documents').replaceChildren();for(const row of rows){const b=el('button',row.title);b.onclick=()=>act(async()=>{if(dirty())throw Error('请先保存或清空未保存内容，再切换文档');selected=row.id;$('#document-title').textContent=row.title;$('#result').hidden=true;current=null;$('#manual-impact').replaceChildren();delete $('#manual-impact').dataset.baseline;$('#impact-list').replaceChildren();await versions();});$('#documents').append(b);}}
async function versions(){const rows=await api('documents/'+selected+'/versions');for(const name of ['old_id','new_id']){const s=$(`#compare [name=${name}]`);s.replaceChildren();for(const row of rows){const o=el('option',`v${row.number} · ${row.label}`);o.value=row.id;s.append(o);}}if(rows.length>1){$('#compare [name=old_id]').value=rows[rows.length-2].id;$('#compare [name=new_id]').value=rows[rows.length-1].id;}}
$('#create').onsubmit=e=>{e.preventDefault();act(async()=>{if(dirty())throw Error('请先保存或清空未保存内容');const row=await api('documents',values(e.target));selected=row.id;$('#document-title').textContent=row.title;e.target.reset();current=null;$('#result').hidden=true;await documents();await versions();});};
$('#version').onsubmit=e=>{e.preventDefault();act(async()=>{if(!selected)throw Error('请先建立或选择文档');await api('documents/'+selected+'/versions',values(e.target));e.target.reset();await versions();});};
$('#discard').onclick=()=>{if(!busy)$('#version').reset();};
$('#compare').onsubmit=e=>{e.preventDefault();act(async()=>{if(!selected)throw Error('先选择文档');if(dirty())throw Error('正文尚未保存，请先保存或清空再比较');render(await api('comparisons',values(e.target)));await loadReview();});};
function render(data){current=data;$('#brief-view').hidden=true;$('#result').hidden=false;$('#comparison-title').textContent=`${data.old_version.label} → ${data.new_version.label}`;$('#summary').textContent=`${data.diff.change_count} 个连续变更区块 · 比较快照已保存`;$('#diff').replaceChildren();$('#changes').replaceChildren();let count=0;for(const [index,op] of data.diff.operations.entries()){const row=el('article','');row.className='diff-row '+(op.kind==='equal'?'equal':'');row.id='op-'+index;if(op.kind!=='equal'){count++;const link=el('a',`${count} · ${labels[op.kind]}`);link.className='change-link';link.href='#'+row.id;$('#changes').append(link);}for(const [side,title] of [['old','旧版'],['new','新版']]){const cell=el('div','');cell.className=side;cell.append(el('h3',`${title} / ${labels[op.kind]} / ${op[side+'_start']}–${op[side+'_end']}`),el('pre',op[side+'_text']||'（本侧无内容）'));row.append(cell);}$('#diff').append(row);}$('#metadata').textContent=JSON.stringify({id:data.id,created_at:data.created_at,old_sha256:data.diff.old_sha256,new_sha256:data.diff.new_sha256,offset_unit:data.diff.offset_unit,algorithm:data.diff.algorithm},null,2);}
$('#export').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));const a=el('a','');a.href=url;a.download='changelens-'+current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
documents().then(()=>$('#notice').textContent='请选择文档。正文保存在当前工作台，AI说明需人工审核。').catch(e=>$('#notice').textContent=e.message);

function setFieldValue(input,value){input.value=value;if(input.name==='old_quote'||input.name==='new_quote'){input.dataset.rawQuote=value;input.dataset.displayQuote=input.value;}}
function values(form){return Object.fromEntries([...form.elements].filter(node=>node.name).map(node=>[node.name,node.dataset.rawQuote!==undefined&&node.value===node.dataset.displayQuote?node.dataset.rawQuote:node.value]));}
function reviewDirty(except=null){return [...document.querySelectorAll('[data-baseline]')].some(f=>f!==except&&JSON.stringify(values(f))!==f.dataset.baseline);}
function cleanOthers(form=null){if(reviewDirty(form))throw Error('还有未保存的说明，请保存或撤销编辑');}
function impactFields(form,item={},withNote=false){
 for(const [name,title,max] of [['summary','影响说明',1500],['old_quote','旧版连续引用（本侧空白时留空）',4000],['new_quote','新版连续引用（本侧空白时留空）',4000],...(withNote?[['note','审核或修订理由',1000]]:[])]){
 const label=el('label',title),input=el('textarea','');input.name=name;input.maxLength=max;setFieldValue(input,item[name]||'');input.required=name==='summary'||name==='note';if(input.required)input.minLength=5;label.append(input);form.append(label);
 }
 form.dataset.baseline=JSON.stringify(values(form));
 const reset=el('button','撤销未保存编辑');reset.type='button';reset.onclick=()=>{if(busy)return;for(const [key,value] of Object.entries(JSON.parse(form.dataset.baseline)))setFieldValue(form.elements.namedItem(key),value);};form.append(reset);
}
async function loadReview(){
 const cid=current.id;const [items,runs,briefs]=await Promise.all([api('comparisons/'+cid+'/impacts'),api('comparisons/'+cid+'/model-runs'),api('comparisons/'+cid+'/briefs')]);if(current?.id!==cid)return;
 const select=$('#operation'),previous=select.value;select.replaceChildren();for(const [i,op] of current.diff.operations.entries()){if(op.kind==='equal')continue;const option=el('option',`变更块 #${i} · ${labels[op.kind]}`);option.value=i;select.append(option);}if([...select.options].some(o=>o.value===previous))select.value=previous;
 const manual=$('#manual-impact');manual.replaceChildren(el('h3','手工补充说明'));impactFields(manual);
 let draftOperation=select.value;
 select.onchange=()=>{if(JSON.stringify(values(manual))!==manual.dataset.baseline){select.value=draftOperation;$('#notice').textContent='当前变更块还有未保存的说明，请先保存或撤销编辑再切换';return;}draftOperation=select.value;};
 const quoteButton=el('button','填入此块原文引用');quoteButton.type='button';
 quoteButton.onclick=()=>{if(busy)return;const op=current.diff.operations[select.value];if(!op){$('#notice').textContent='没有可引用的变更块';return;}if([...op.old_text].length>4000||[...op.new_text].length>4000){$('#notice').textContent='变更块超过单侧4000字符引用限制，请手工选择连续片段';return;}setFieldValue(manual.elements.namedItem('old_quote'),op.old_text);setFieldValue(manual.elements.namedItem('new_quote'),op.new_text);$('#notice').textContent='已填入当前块的完整原文引用。请补充说明，核对否定、条件和数字后保存。';};
 manual.append(quoteButton,el('button','保存说明草稿'));
 manual.onsubmit=e=>{e.preventDefault();act(async()=>{cleanOthers(manual);await api(`comparisons/${cid}/operations/${select.value}/impacts`,values(manual));await loadReview();});};
 $('#impact-list').replaceChildren();for(const item of items){const form=el('form','');form.className='impact-card';form.append(el('h3',`变更块 #${item.operation} · ${{draft:'待审核',confirmed:'已确认',rejected:'已拒绝'}[item.state]} · v${item.version}`));impactFields(form,item,true);form.append(el('button','保存修订并重新审核'));
 form.onsubmit=e=>{e.preventDefault();act(async()=>{cleanOthers(form);await api('impacts/'+item.id+'/revise',{...values(form),version:item.version});await loadReview();});};
 for(const [decision,title] of [['confirmed','确认当前说明'],['rejected','拒绝当前说明']]){const b=el('button',title);b.type='button';b.disabled=item.state===decision;b.onclick=()=>act(async()=>{cleanOthers(form);const v=values(form);if(['summary','old_quote','new_quote'].some(k=>v[k]!==item[k]))throw Error('请先保存修订，再审核新版本');if(v.note.trim().length<5)throw Error('请填写至少5字审核理由');await api('impacts/'+item.id+'/review',{version:item.version,decision,note:v.note});await loadReview();});form.append(b);}
 const history=el('button','查看说明历史');history.type='button';history.onclick=()=>act(async()=>{let pre=form.querySelector('pre');if(!pre){pre=el('pre','');form.append(pre);}pre.textContent=JSON.stringify(await api('impacts/'+item.id+'/history'),null,2);});form.append(history);$('#impact-list').append(form);}
 showRuns(runs);$('#brief-list').replaceChildren();for(const brief of briefs){const b=el('button',brief.title+' · '+new Date(brief.created_at).toLocaleString());b.onclick=()=>act(()=>showBrief(brief.id));$('#brief-list').append(b);}
}
function showRuns(runs){$('#run-list').replaceChildren();for(const run of runs){const d=el('details','');d.append(el('summary',`变更块 #${run.operation} · ${run.error||'草稿已保存，需人工核对'}`),el('pre',run.raw||'无模型输出'),el('pre',run.metadata));$('#run-list').append(d);}}
$('#suggest-impact').onclick=()=>act(async()=>{cleanOthers();if(!current||$('#operation').value==='')throw Error('没有可分析的变更块');$('#notice').textContent='本地模型处理中…';try{await api(`comparisons/${current.id}/operations/${$('#operation').value}/suggest`,{});}finally{await loadReview();}});
$('#reload-runs').onclick=()=>act(async()=>showRuns(await api('comparisons/'+current.id+'/model-runs')));
$('#brief-form').onsubmit=e=>{e.preventDefault();act(async()=>{cleanOthers();const brief=await api('comparisons/'+current.id+'/briefs',values(e.target));await loadReview();await showBrief(brief.id);});};
async function showBrief(id){const brief=await api('briefs/'+id),box=$('#brief-view');box.hidden=false;box.replaceChildren(el('h3',brief.title),el('p',brief.note),el('p',`已确认说明 ${brief.confirmed_impacts.length} 条；尚无已确认说明的变更块：${brief.unreviewed_operations.length?brief.unreviewed_operations.map(i=>'#'+i).join('、'):'无'}`));for(const item of brief.confirmed_impacts)box.append(el('h4',`变更块 #${item.operation}`),el('p',item.summary),el('pre',`旧版：${item.old_quote||'（无）'}\n新版：${item.new_quote||'（无）'}`));const d=el('details','');d.append(el('summary','查看完整冻结证据'),el('pre',JSON.stringify(brief,null,2)));box.append(d);const download=el('a','下载完整简报 ZIP');download.className='change-link';download.href='/api/briefs/'+encodeURIComponent(id)+'/export';download.download='changelens-brief.zip';box.append(download);}

$('#import-version').onsubmit=e=>{e.preventDefault();act(async()=>{if(!selected)throw Error('先选择文档');if(dirty())throw Error('请先保存或清空未保存内容');const file=$('#version-file').files[0];if(!file)throw Error('请选择文本文件');if(file.size>80000)throw Error('文件超过80KB');const response=await fetch('/api/documents/'+selected+'/versions/file?label='+encodeURIComponent(values(e.target).label),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});const result=await response.json();if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:'导入失败');e.target.reset();await versions();});};
